import { CaViolationsItemBase } from './CaViolationsItemBase';
export interface CaViolationsItem extends CaViolationsItemBase {
    CaseName?: string;
    CaseNumber?: string;
    CaseStatus?: string;
    CaseStatusID?: number;
    CaseType?: string;
    CaseTypeDesc?: string;
    CaseTypeId?: number;
    CompletedByLoginId?: string;
    CreatedByLoginId?: string;
    FeeCode?: string;
    FeeDesc?: string;
    FeeSetupId?: number;
    IsSingleEntry?: boolean;
    IssuedByLoginId?: string;
    Location?: string;
    ModifiedByLoginId?: string;
    ProjectCode?: string;
    ProjectDesc?: string;
    ProjectId?: number;
    StatusCode?: string;
    SubType?: string;
    SubTypeDesc?: string;
    SubTypeId?: number;
    TableName?: string;
    TaskCode?: string;
    TaskDesc?: string;
    ViolationDesc?: string;
    ViolationType?: string;
}
