import { StoreDomainBase } from './StoreDomainBase';
import { GISRight } from './GISRight';
import { CWDomain } from './CWDomain';
export interface CWUser {
    ADDomain?: string;
    Districts?: string[];
    DomainId?: number;
    Domains?: CWDomain[];
    EmployeeSid?: number;
    FullName?: string;
    GISRight?: GISRight;
    GroupId?: number;
    GroupIds?: string;
    Groups?: number[];
    IsCwdba?: boolean;
    IsDomainSuperuser?: boolean;
    IsPAGuestUser?: boolean;
    IsPARegisteredUser?: boolean;
    IsWindowsIdentity?: boolean;
    LoginId?: string;
    LoginName?: string;
    MembershipId?: number;
    OrgId?: number;
    RoleId?: string;
    Roles?: string;
    StoreDomainId?: number;
    StoreDomainsWhereAdmin?: StoreDomainBase[];
    TableName?: string;
    UniqueName?: string;
    UserId?: number;
    UserName?: string;
    UserPwd?: string;
    UserType?: string;
}
