export interface DivisionItem {
    AddressLine1?: string;
    AddressLine2?: string;
    AddressLine3?: string;
    CityName?: string;
    CountryCode?: string;
    CountryName?: string;
    CreatedBy?: number;
    CreatedByLoginId?: string;
    DateCreated?: Date;
    DateExpired?: Date;
    DateModified?: Date;
    DepartmentCode?: string;
    DepartmentId?: number;
    DepartmentName?: string;
    DivisionCode?: string;
    DivisionId?: number;
    DivisionName?: string;
    ExpiredFlag?: string;
    FaxNumber?: string;
    ModifiedBy?: number;
    ModifiedByLoginId?: string;
    OrgId?: number;
    PhoneNumber?: string;
    PhoneNumberExt?: string;
    StateCode?: string;
    StateName?: string;
    ZipCode?: string;
}
