import { ApplyLevel } from './ApplyLevel';
import { SearchType } from './SearchType';
export interface EventLayer {
    AssetUrl?: string;
    CityworksDescriptionFieldName?: string;
    CityworksEntitySidFieldName?: string;
    CityworksEntityTypeFieldName?: string;
    CityworksEntityUidFieldName?: string;
    CityworksTemplateFieldName?: string;
    Description?: string;
    DomainFieldName?: string;
    DomainId?: number;
    Enabled?: boolean;
    EventKeyField?: string;
    EventType?: SearchType;
    FillColor?: string;
    FillSymbolEnum?: number;
    ImageURL?: string;
    LayerId?: number;
    LayerName?: string;
    LineSymbolEnum?: number;
    MapUrl?: string;
    MarkerSymbolEnum?: number;
    MarkerSymbolSize?: number;
    OffsetX?: number;
    OffsetY?: number;
    OutlineColor?: string;
    OutlineColorWidth?: number;
    RefreshInterval?: number;
    SearchId?: number;
    SearchName?: string;
    SharedWithin?: ApplyLevel;
    StatusFieldName?: string;
    TableName?: string;
    TableSqlAlias?: string;
    UserId?: number;
    XField?: string;
    YField?: string;
}
