export declare enum EventSourceType {
    Request = 0,
    WorkOrder = 1,
    Inspection = 2,
    Permit = 3,
    Comment = 4,
    WorkOrderLabor = 5,
    RequestLabor = 6,
    Unknown = 7,
    SMS = 8,
    CaTaskItem = 9,
    WoTask = 10,
    RequestAttachment = 11,
    WorkOrderAttachment = 12,
    InspectionAttachment = 13,
    CaRelDocs = 14,
}
