export declare enum GISServiceType {
    DYNAMICMAP = 0,
    TILEDMAP = 1,
    IMAGEMAP = 2,
    GEOCODE = 3,
    GEOMETRY = 4,
    FEATURELAYER = 5,
    WEBMAP = 6,
    HEATMAP = 7,
    KMLLAYER = 8,
    WMSLAYER = 9,
    GEODATA = 10,
    SOE = 11,
    UNKNOWN = 12,
    RESOURCEPROXY = 13,
    TILEPACKAGE = 14,
    PRINTING = 15,
    ROUTING = 16,
    VECTORTILE = 17,
    MOBILEMAPPACKAGE = 18,
}
