import { MaterialCostType } from './MaterialCostType';
import { AbcCatClass } from './AbcCatClass';
export interface MaterialBase {
    AuditInterval?: string;
    BinImagePath?: string;
    BinLocation?: string;
    CatClass?: AbcCatClass;
    Category?: string;
    CostType?: MaterialCostType;
    CUCategory?: string;
    Custom1?: number;
    Custom2?: number;
    Custom3?: string;
    Custom4?: string;
    Custom5?: string;
    DefaultImgPath?: string;
    Description?: string;
    Detail?: string;
    ExpirationDate?: Date;
    GdbSubtype?: string;
    GdbTableName?: string;
    IsAssembly?: boolean;
    JustificationRequired?: boolean;
    Manufacturer?: string;
    MaterialSid?: number;
    MaterialUid?: string;
    MinQuantity?: number;
    Model?: string;
    PartNumber?: string;
    SecBinImagePath?: string;
    SecBinLocation?: string;
    Splittable?: boolean;
    StockOnHand?: number;
    Storeroom?: string;
    Supplier?: string;
    UnitCost?: number;
    UnitOfMeasure?: string;
    Viewable?: boolean;
}
