import { CostUsage } from './CostUsage';
import { LaborRateType } from './LaborRateType';
import { LaborCategory } from './LaborCategory';
import { LaborCostDetail } from './LaborCostDetail';
export interface WorkOrderLaborCost {
    AcctNum?: string;
    BenefitCost?: number;
    ContractorNumber?: string;
    Cost?: number;
    Description?: string;
    DomainId?: number;
    EntityType?: string;
    EntityUid?: string;
    FinishDate?: Date;
    GroupName?: string;
    HolidayCost?: number;
    Hours?: number;
    LaborCostDetails?: LaborCostDetail[];
    LaborCostId?: number;
    LaborName?: string;
    LaborSid?: number;
    LaborType?: LaborCategory;
    OccupationCode?: string;
    OccupationId?: number;
    OtherCost?: number;
    OverheadCost?: number;
    OvertimeCost?: number;
    RateType?: LaborRateType;
    RegularCost?: number;
    ShiftDiffCost?: number;
    StandbyCost?: number;
    StartDate?: Date;
    TaskName?: string;
    TimesheetId?: number;
    TransDate?: Date;
    UsageType?: CostUsage;
    WorkOrderId?: string;
    WorkOrderSid?: number;
    WOTaskId?: number;
}
