import { WOOutputType } from './WOOutputType';
import { WOStage } from './WOStage';
import { WOExpenseType } from './WOExpenseType';
import { RepeatType } from './RepeatType';
import { RepeatIntervalUnit } from './RepeatIntervalUnit';
import { RepeatFromDate } from './RepeatFromDate';
import { CustomFieldValueSource } from './CustomFieldValueSource';
export interface WOTemplateBase {
    AcctNum?: string;
    ApplyToEntity?: string;
    AutoCreateTask?: boolean;
    Cancel?: boolean;
    Comments?: string;
    CopyCustomFieldVal?: CustomFieldValueSource;
    CreateDate?: Date;
    CycleFrom?: RepeatFromDate;
    CycleIncludeWeekends?: boolean;
    CycleIntervalNum?: number;
    CycleIntervalUnit?: RepeatIntervalUnit;
    CycleType?: RepeatType;
    DateModified?: Date;
    DaysToComplete?: number;
    DefaultProject?: string;
    DefaultProjectSid?: number;
    Description?: string;
    DomainId?: number;
    Effort?: number;
    ExpenseType?: WOExpenseType;
    Instructions?: string;
    IsReactive?: boolean;
    MaintScore?: number;
    MapTemplateName?: string;
    NumDaysBefore?: number;
    Printer?: string;
    Priority?: string;
    RequireAssetOnClose?: boolean;
    Shop?: string;
    Stage?: WOStage;
    Status?: string;
    SubmitToEmployeeSid?: number;
    SupervisorEmployeeSid?: number;
    UnitsAccompDesc?: string;
    UnitsAccompDescLock?: boolean;
    WarrantyDuration?: number;
    WarrantyDurationUnit?: RepeatIntervalUnit;
    WOCategory?: string;
    WOCustFieldCatId?: number;
    WOMapExtent?: string;
    WOMapScale?: number;
    WOOutput?: WOOutputType;
    WOPrintTmpt?: string;
    WorkMonth?: string;
    WOTemplateId?: string;
}
