import { ChgOutReadConfig } from '../core/types/ChgOutReadConfig';
import { EquipmentChangeOutHistory } from '../core/types/EquipmentChangeOutHistory';
import { WorkOrderEntity } from '../core/types/WorkOrderEntity';
import { ParentChildItem } from '../core/types/ParentChildItem';
import { EquipChangeOutBase } from '../core/types/EquipChangeOutBase';
import { EquipChangeOut } from '../core/types/EquipChangeOut';
import { ChangeOutOperation } from '../core/types/ChangeOutOperation';
import { ChangeOutRead } from '../core/types/ChangeOutRead';
import { ServiceTypes } from '../core/service-types';
export declare namespace EquipmentChangeOutServiceTypes {
    namespace Requests {
        interface AddChangeOutRead extends ServiceTypes.CoreRequestBase {
            ChangeOutId: number;
            Date1?: Date;
            Date2?: Date;
            Date3?: Date;
            Date4?: Date;
            Date5?: Date;
            IsNewRead?: boolean;
            Num1?: number;
            Num10?: number;
            Num11?: number;
            Num12?: number;
            Num13?: number;
            Num14?: number;
            Num15?: number;
            Num16?: number;
            Num17?: number;
            Num18?: number;
            Num19?: number;
            Num2?: number;
            Num20?: number;
            Num3?: number;
            Num4?: number;
            Num5?: number;
            Num6?: number;
            Num7?: number;
            Num8?: number;
            Num9?: number;
            OperationId: number;
            Text1?: string;
            Text10?: string;
            Text11?: string;
            Text12?: string;
            Text13?: string;
            Text14?: string;
            Text15?: string;
            Text16?: string;
            Text17?: string;
            Text18?: string;
            Text19?: string;
            Text2?: string;
            Text20?: string;
            Text3?: string;
            Text4?: string;
            Text5?: string;
            Text6?: string;
            Text7?: string;
            Text8?: string;
            Text9?: string;
        }
        interface AddOperation extends ServiceTypes.CoreRequestBase {
            AssetType?: string;
            ChangeOutId: number;
            NewRead_Date1?: Date;
            NewRead_Date2?: Date;
            NewRead_Date3?: Date;
            NewRead_Date4?: Date;
            NewRead_Date5?: Date;
            NewRead_Id?: number;
            NewRead_Num1?: number;
            NewRead_Num10?: number;
            NewRead_Num11?: number;
            NewRead_Num12?: number;
            NewRead_Num13?: number;
            NewRead_Num14?: number;
            NewRead_Num15?: number;
            NewRead_Num16?: number;
            NewRead_Num17?: number;
            NewRead_Num18?: number;
            NewRead_Num19?: number;
            NewRead_Num2?: number;
            NewRead_Num20?: number;
            NewRead_Num3?: number;
            NewRead_Num4?: number;
            NewRead_Num5?: number;
            NewRead_Num6?: number;
            NewRead_Num7?: number;
            NewRead_Num8?: number;
            NewRead_Num9?: number;
            NewRead_Text1?: string;
            NewRead_Text10?: string;
            NewRead_Text11?: string;
            NewRead_Text12?: string;
            NewRead_Text13?: string;
            NewRead_Text14?: string;
            NewRead_Text15?: string;
            NewRead_Text16?: string;
            NewRead_Text17?: string;
            NewRead_Text18?: string;
            NewRead_Text19?: string;
            NewRead_Text2?: string;
            NewRead_Text20?: string;
            NewRead_Text3?: string;
            NewRead_Text4?: string;
            NewRead_Text5?: string;
            NewRead_Text6?: string;
            NewRead_Text7?: string;
            NewRead_Text8?: string;
            NewRead_Text9?: string;
            NewUid?: string;
            OldRead_Date1?: Date;
            OldRead_Date2?: Date;
            OldRead_Date3?: Date;
            OldRead_Date4?: Date;
            OldRead_Date5?: Date;
            OldRead_Id?: number;
            OldRead_Num1?: number;
            OldRead_Num10?: number;
            OldRead_Num11?: number;
            OldRead_Num12?: number;
            OldRead_Num13?: number;
            OldRead_Num14?: number;
            OldRead_Num15?: number;
            OldRead_Num16?: number;
            OldRead_Num17?: number;
            OldRead_Num18?: number;
            OldRead_Num19?: number;
            OldRead_Num2?: number;
            OldRead_Num20?: number;
            OldRead_Num3?: number;
            OldRead_Num4?: number;
            OldRead_Num5?: number;
            OldRead_Num6?: number;
            OldRead_Num7?: number;
            OldRead_Num8?: number;
            OldRead_Num9?: number;
            OldRead_Text1?: string;
            OldRead_Text10?: string;
            OldRead_Text11?: string;
            OldRead_Text12?: string;
            OldRead_Text13?: string;
            OldRead_Text14?: string;
            OldRead_Text15?: string;
            OldRead_Text16?: string;
            OldRead_Text17?: string;
            OldRead_Text18?: string;
            OldRead_Text19?: string;
            OldRead_Text2?: string;
            OldRead_Text20?: string;
            OldRead_Text3?: string;
            OldRead_Text4?: string;
            OldRead_Text5?: string;
            OldRead_Text6?: string;
            OldRead_Text7?: string;
            OldRead_Text8?: string;
            OldRead_Text9?: string;
            OldUid?: string;
            Operation: number;
            OperationComments?: string;
            RecordDate?: Date;
        }
        interface Attach extends ServiceTypes.CoreRequestBase {
            AssetType?: string;
            ChangeDate?: Date;
            ChangedById?: number;
            ChangeOutId?: number;
            Comments?: string;
            Date1?: Date;
            Date2?: Date;
            Date3?: Date;
            Date4?: Date;
            Date5?: Date;
            FeatureSid?: number;
            FeatureType?: string;
            FeatureUid?: string;
            InspCustFieldCatId?: number;
            InspectedBySid?: number;
            Location?: string;
            NewRead_Date1?: Date;
            NewRead_Date2?: Date;
            NewRead_Date3?: Date;
            NewRead_Date4?: Date;
            NewRead_Date5?: Date;
            NewRead_Id?: number;
            NewRead_Num1?: number;
            NewRead_Num10?: number;
            NewRead_Num11?: number;
            NewRead_Num12?: number;
            NewRead_Num13?: number;
            NewRead_Num14?: number;
            NewRead_Num15?: number;
            NewRead_Num16?: number;
            NewRead_Num17?: number;
            NewRead_Num18?: number;
            NewRead_Num19?: number;
            NewRead_Num2?: number;
            NewRead_Num20?: number;
            NewRead_Num3?: number;
            NewRead_Num4?: number;
            NewRead_Num5?: number;
            NewRead_Num6?: number;
            NewRead_Num7?: number;
            NewRead_Num8?: number;
            NewRead_Num9?: number;
            NewRead_Text1?: string;
            NewRead_Text10?: string;
            NewRead_Text11?: string;
            NewRead_Text12?: string;
            NewRead_Text13?: string;
            NewRead_Text14?: string;
            NewRead_Text15?: string;
            NewRead_Text16?: string;
            NewRead_Text17?: string;
            NewRead_Text18?: string;
            NewRead_Text19?: string;
            NewRead_Text2?: string;
            NewRead_Text20?: string;
            NewRead_Text3?: string;
            NewRead_Text4?: string;
            NewRead_Text5?: string;
            NewRead_Text6?: string;
            NewRead_Text7?: string;
            NewRead_Text8?: string;
            NewRead_Text9?: string;
            NewUid?: string;
            Num1?: number;
            Num10?: number;
            Num11?: number;
            Num12?: number;
            Num13?: number;
            Num14?: number;
            Num15?: number;
            Num16?: number;
            Num17?: number;
            Num18?: number;
            Num19?: number;
            Num2?: number;
            Num20?: number;
            Num3?: number;
            Num4?: number;
            Num5?: number;
            Num6?: number;
            Num7?: number;
            Num8?: number;
            Num9?: number;
            OperationComments?: string;
            OperationId?: number;
            RecordDate?: Date;
            Text1?: string;
            Text10?: string;
            Text11?: string;
            Text12?: string;
            Text13?: string;
            Text14?: string;
            Text15?: string;
            Text16?: string;
            Text17?: string;
            Text18?: string;
            Text19?: string;
            Text2?: string;
            Text20?: string;
            Text3?: string;
            Text4?: string;
            Text5?: string;
            Text6?: string;
            Text7?: string;
            Text8?: string;
            Text9?: string;
            UpdateMap?: boolean;
            WorkOrderId?: string;
            WorkOrderSid?: number;
        }
        interface ById extends ServiceTypes.CoreRequestBase {
            ChangeOutId?: number;
        }
        interface ByIds extends ServiceTypes.CoreRequestBase {
            ChangeOutIds?: number[];
        }
        interface Delete extends ServiceTypes.CoreRequestBase {
            ChangeOutId: number;
            ChangeOutIds: number[];
        }
        interface DeleteChangeOutReads extends ServiceTypes.CoreRequestBase {
            ReadIds: number[];
        }
        interface DeleteOperations extends ServiceTypes.CoreRequestBase {
            OperationIds: number[];
        }
        interface Detach extends ServiceTypes.CoreRequestBase {
            AssetType?: string;
            ChangeDate?: Date;
            ChangedById?: number;
            ChangeOutId?: number;
            Comments?: string;
            Date1?: Date;
            Date2?: Date;
            Date3?: Date;
            Date4?: Date;
            Date5?: Date;
            FeatureSid?: number;
            FeatureType?: string;
            FeatureUid?: string;
            InspCustFieldCatId?: number;
            InspectedBySid?: number;
            Location?: string;
            Num1?: number;
            Num10?: number;
            Num11?: number;
            Num12?: number;
            Num13?: number;
            Num14?: number;
            Num15?: number;
            Num16?: number;
            Num17?: number;
            Num18?: number;
            Num19?: number;
            Num2?: number;
            Num20?: number;
            Num3?: number;
            Num4?: number;
            Num5?: number;
            Num6?: number;
            Num7?: number;
            Num8?: number;
            Num9?: number;
            OldRead_Date1?: Date;
            OldRead_Date2?: Date;
            OldRead_Date3?: Date;
            OldRead_Date4?: Date;
            OldRead_Date5?: Date;
            OldRead_Id?: number;
            OldRead_Num1?: number;
            OldRead_Num10?: number;
            OldRead_Num11?: number;
            OldRead_Num12?: number;
            OldRead_Num13?: number;
            OldRead_Num14?: number;
            OldRead_Num15?: number;
            OldRead_Num16?: number;
            OldRead_Num17?: number;
            OldRead_Num18?: number;
            OldRead_Num19?: number;
            OldRead_Num2?: number;
            OldRead_Num20?: number;
            OldRead_Num3?: number;
            OldRead_Num4?: number;
            OldRead_Num5?: number;
            OldRead_Num6?: number;
            OldRead_Num7?: number;
            OldRead_Num8?: number;
            OldRead_Num9?: number;
            OldRead_Text1?: string;
            OldRead_Text10?: string;
            OldRead_Text11?: string;
            OldRead_Text12?: string;
            OldRead_Text13?: string;
            OldRead_Text14?: string;
            OldRead_Text15?: string;
            OldRead_Text16?: string;
            OldRead_Text17?: string;
            OldRead_Text18?: string;
            OldRead_Text19?: string;
            OldRead_Text2?: string;
            OldRead_Text20?: string;
            OldRead_Text3?: string;
            OldRead_Text4?: string;
            OldRead_Text5?: string;
            OldRead_Text6?: string;
            OldRead_Text7?: string;
            OldRead_Text8?: string;
            OldRead_Text9?: string;
            OldUid?: string;
            OperationComments?: string;
            OperationId?: number;
            RecordDate?: Date;
            Text1?: string;
            Text10?: string;
            Text11?: string;
            Text12?: string;
            Text13?: string;
            Text14?: string;
            Text15?: string;
            Text16?: string;
            Text17?: string;
            Text18?: string;
            Text19?: string;
            Text2?: string;
            Text20?: string;
            Text3?: string;
            Text4?: string;
            Text5?: string;
            Text6?: string;
            Text7?: string;
            Text8?: string;
            Text9?: string;
            UpdateMap?: boolean;
            WorkOrderId?: string;
            WorkOrderSid?: number;
        }
        interface DirectParent extends ServiceTypes.CoreRequestBase {
            EntitySid: number;
            EntityType: string;
            EntityUid: string;
            ParentType?: string;
        }
        interface Entities extends ServiceTypes.CoreRequestBase {
            EntitySids: number[];
            EntityType: string;
            EntityUids: string[];
            ReadableValues?: boolean;
        }
        interface Entity extends ServiceTypes.CoreRequestBase {
            EntitySid?: number;
            EntityType?: string;
            EntityUid?: string;
        }
        interface History extends ServiceTypes.CoreRequestBase {
            EntityType?: string;
            EntityUid?: string;
        }
        interface Read extends ServiceTypes.CoreRequestBase {
            AssetType?: string;
            ChangeDate?: Date;
            ChangedById?: number;
            ChangeOutId?: number;
            Comments?: string;
            Date1?: Date;
            Date2?: Date;
            Date3?: Date;
            Date4?: Date;
            Date5?: Date;
            FeatureSid?: number;
            FeatureType?: string;
            FeatureUid?: string;
            InspCustFieldCatId?: number;
            InspectedBySid?: number;
            Location?: string;
            NewRead_Date1?: Date;
            NewRead_Date2?: Date;
            NewRead_Date3?: Date;
            NewRead_Date4?: Date;
            NewRead_Date5?: Date;
            NewRead_Id?: number;
            NewRead_Num1?: number;
            NewRead_Num10?: number;
            NewRead_Num11?: number;
            NewRead_Num12?: number;
            NewRead_Num13?: number;
            NewRead_Num14?: number;
            NewRead_Num15?: number;
            NewRead_Num16?: number;
            NewRead_Num17?: number;
            NewRead_Num18?: number;
            NewRead_Num19?: number;
            NewRead_Num2?: number;
            NewRead_Num20?: number;
            NewRead_Num3?: number;
            NewRead_Num4?: number;
            NewRead_Num5?: number;
            NewRead_Num6?: number;
            NewRead_Num7?: number;
            NewRead_Num8?: number;
            NewRead_Num9?: number;
            NewRead_Text1?: string;
            NewRead_Text10?: string;
            NewRead_Text11?: string;
            NewRead_Text12?: string;
            NewRead_Text13?: string;
            NewRead_Text14?: string;
            NewRead_Text15?: string;
            NewRead_Text16?: string;
            NewRead_Text17?: string;
            NewRead_Text18?: string;
            NewRead_Text19?: string;
            NewRead_Text2?: string;
            NewRead_Text20?: string;
            NewRead_Text3?: string;
            NewRead_Text4?: string;
            NewRead_Text5?: string;
            NewRead_Text6?: string;
            NewRead_Text7?: string;
            NewRead_Text8?: string;
            NewRead_Text9?: string;
            NewUid?: string;
            Num1?: number;
            Num10?: number;
            Num11?: number;
            Num12?: number;
            Num13?: number;
            Num14?: number;
            Num15?: number;
            Num16?: number;
            Num17?: number;
            Num18?: number;
            Num19?: number;
            Num2?: number;
            Num20?: number;
            Num3?: number;
            Num4?: number;
            Num5?: number;
            Num6?: number;
            Num7?: number;
            Num8?: number;
            Num9?: number;
            OldRead_Date1?: Date;
            OldRead_Date2?: Date;
            OldRead_Date3?: Date;
            OldRead_Date4?: Date;
            OldRead_Date5?: Date;
            OldRead_Id?: number;
            OldRead_Num1?: number;
            OldRead_Num10?: number;
            OldRead_Num11?: number;
            OldRead_Num12?: number;
            OldRead_Num13?: number;
            OldRead_Num14?: number;
            OldRead_Num15?: number;
            OldRead_Num16?: number;
            OldRead_Num17?: number;
            OldRead_Num18?: number;
            OldRead_Num19?: number;
            OldRead_Num2?: number;
            OldRead_Num20?: number;
            OldRead_Num3?: number;
            OldRead_Num4?: number;
            OldRead_Num5?: number;
            OldRead_Num6?: number;
            OldRead_Num7?: number;
            OldRead_Num8?: number;
            OldRead_Num9?: number;
            OldRead_Text1?: string;
            OldRead_Text10?: string;
            OldRead_Text11?: string;
            OldRead_Text12?: string;
            OldRead_Text13?: string;
            OldRead_Text14?: string;
            OldRead_Text15?: string;
            OldRead_Text16?: string;
            OldRead_Text17?: string;
            OldRead_Text18?: string;
            OldRead_Text19?: string;
            OldRead_Text2?: string;
            OldRead_Text20?: string;
            OldRead_Text3?: string;
            OldRead_Text4?: string;
            OldRead_Text5?: string;
            OldRead_Text6?: string;
            OldRead_Text7?: string;
            OldRead_Text8?: string;
            OldRead_Text9?: string;
            OldUid?: string;
            OperationComments?: string;
            OperationId?: number;
            RecordDate?: Date;
            Text1?: string;
            Text10?: string;
            Text11?: string;
            Text12?: string;
            Text13?: string;
            Text14?: string;
            Text15?: string;
            Text16?: string;
            Text17?: string;
            Text18?: string;
            Text19?: string;
            Text2?: string;
            Text20?: string;
            Text3?: string;
            Text4?: string;
            Text5?: string;
            Text6?: string;
            Text7?: string;
            Text8?: string;
            Text9?: string;
            UpdateMap?: boolean;
            WorkOrderId?: string;
            WorkOrderSid?: number;
        }
        interface ReadConfigs extends ServiceTypes.CoreRequestBase {
            EntityType: string;
            EntityTypes?: string[];
        }
        interface Related extends ServiceTypes.CoreRequestBase {
            EntitySid: number;
            EntityType: string;
            EntityUid: string;
        }
        interface Replace extends ServiceTypes.CoreRequestBase {
            AssetType?: string;
            ChangeDate?: Date;
            ChangedById?: number;
            ChangeOutId?: number;
            Comments?: string;
            Date1?: Date;
            Date2?: Date;
            Date3?: Date;
            Date4?: Date;
            Date5?: Date;
            FeatureSid?: number;
            FeatureType?: string;
            FeatureUid?: string;
            InspCustFieldCatId?: number;
            InspectedBySid?: number;
            Location?: string;
            NewRead_Date1?: Date;
            NewRead_Date2?: Date;
            NewRead_Date3?: Date;
            NewRead_Date4?: Date;
            NewRead_Date5?: Date;
            NewRead_Id?: number;
            NewRead_Num1?: number;
            NewRead_Num10?: number;
            NewRead_Num11?: number;
            NewRead_Num12?: number;
            NewRead_Num13?: number;
            NewRead_Num14?: number;
            NewRead_Num15?: number;
            NewRead_Num16?: number;
            NewRead_Num17?: number;
            NewRead_Num18?: number;
            NewRead_Num19?: number;
            NewRead_Num2?: number;
            NewRead_Num20?: number;
            NewRead_Num3?: number;
            NewRead_Num4?: number;
            NewRead_Num5?: number;
            NewRead_Num6?: number;
            NewRead_Num7?: number;
            NewRead_Num8?: number;
            NewRead_Num9?: number;
            NewRead_Text1?: string;
            NewRead_Text10?: string;
            NewRead_Text11?: string;
            NewRead_Text12?: string;
            NewRead_Text13?: string;
            NewRead_Text14?: string;
            NewRead_Text15?: string;
            NewRead_Text16?: string;
            NewRead_Text17?: string;
            NewRead_Text18?: string;
            NewRead_Text19?: string;
            NewRead_Text2?: string;
            NewRead_Text20?: string;
            NewRead_Text3?: string;
            NewRead_Text4?: string;
            NewRead_Text5?: string;
            NewRead_Text6?: string;
            NewRead_Text7?: string;
            NewRead_Text8?: string;
            NewRead_Text9?: string;
            NewUid?: string;
            Num1?: number;
            Num10?: number;
            Num11?: number;
            Num12?: number;
            Num13?: number;
            Num14?: number;
            Num15?: number;
            Num16?: number;
            Num17?: number;
            Num18?: number;
            Num19?: number;
            Num2?: number;
            Num20?: number;
            Num3?: number;
            Num4?: number;
            Num5?: number;
            Num6?: number;
            Num7?: number;
            Num8?: number;
            Num9?: number;
            OldRead_Date1?: Date;
            OldRead_Date2?: Date;
            OldRead_Date3?: Date;
            OldRead_Date4?: Date;
            OldRead_Date5?: Date;
            OldRead_Id?: number;
            OldRead_Num1?: number;
            OldRead_Num10?: number;
            OldRead_Num11?: number;
            OldRead_Num12?: number;
            OldRead_Num13?: number;
            OldRead_Num14?: number;
            OldRead_Num15?: number;
            OldRead_Num16?: number;
            OldRead_Num17?: number;
            OldRead_Num18?: number;
            OldRead_Num19?: number;
            OldRead_Num2?: number;
            OldRead_Num20?: number;
            OldRead_Num3?: number;
            OldRead_Num4?: number;
            OldRead_Num5?: number;
            OldRead_Num6?: number;
            OldRead_Num7?: number;
            OldRead_Num8?: number;
            OldRead_Num9?: number;
            OldRead_Text1?: string;
            OldRead_Text10?: string;
            OldRead_Text11?: string;
            OldRead_Text12?: string;
            OldRead_Text13?: string;
            OldRead_Text14?: string;
            OldRead_Text15?: string;
            OldRead_Text16?: string;
            OldRead_Text17?: string;
            OldRead_Text18?: string;
            OldRead_Text19?: string;
            OldRead_Text2?: string;
            OldRead_Text20?: string;
            OldRead_Text3?: string;
            OldRead_Text4?: string;
            OldRead_Text5?: string;
            OldRead_Text6?: string;
            OldRead_Text7?: string;
            OldRead_Text8?: string;
            OldRead_Text9?: string;
            OldUid?: string;
            OperationComments?: string;
            OperationId?: number;
            RecordDate?: Date;
            Text1?: string;
            Text10?: string;
            Text11?: string;
            Text12?: string;
            Text13?: string;
            Text14?: string;
            Text15?: string;
            Text16?: string;
            Text17?: string;
            Text18?: string;
            Text19?: string;
            Text2?: string;
            Text20?: string;
            Text3?: string;
            Text4?: string;
            Text5?: string;
            Text6?: string;
            Text7?: string;
            Text8?: string;
            Text9?: string;
            UpdateMap?: boolean;
            WorkOrderId?: string;
            WorkOrderSid?: number;
        }
        interface UpdateChangeOutRead extends ServiceTypes.CoreRequestBase {
            Date1?: Date;
            Date2?: Date;
            Date3?: Date;
            Date4?: Date;
            Date5?: Date;
            Num1?: number;
            Num10?: number;
            Num11?: number;
            Num12?: number;
            Num13?: number;
            Num14?: number;
            Num15?: number;
            Num16?: number;
            Num17?: number;
            Num18?: number;
            Num19?: number;
            Num2?: number;
            Num20?: number;
            Num3?: number;
            Num4?: number;
            Num5?: number;
            Num6?: number;
            Num7?: number;
            Num8?: number;
            Num9?: number;
            ReadId: number;
            Text1?: string;
            Text10?: string;
            Text11?: string;
            Text12?: string;
            Text13?: string;
            Text14?: string;
            Text15?: string;
            Text16?: string;
            Text17?: string;
            Text18?: string;
            Text19?: string;
            Text2?: string;
            Text20?: string;
            Text3?: string;
            Text4?: string;
            Text5?: string;
            Text6?: string;
            Text7?: string;
            Text8?: string;
            Text9?: string;
        }
        interface UpdateOperation extends ServiceTypes.CoreRequestBase {
            AssetType?: string;
            ChangeOutId?: number;
            NewRead_Date1?: Date;
            NewRead_Date2?: Date;
            NewRead_Date3?: Date;
            NewRead_Date4?: Date;
            NewRead_Date5?: Date;
            NewRead_Id?: number;
            NewRead_Num1?: number;
            NewRead_Num10?: number;
            NewRead_Num11?: number;
            NewRead_Num12?: number;
            NewRead_Num13?: number;
            NewRead_Num14?: number;
            NewRead_Num15?: number;
            NewRead_Num16?: number;
            NewRead_Num17?: number;
            NewRead_Num18?: number;
            NewRead_Num19?: number;
            NewRead_Num2?: number;
            NewRead_Num20?: number;
            NewRead_Num3?: number;
            NewRead_Num4?: number;
            NewRead_Num5?: number;
            NewRead_Num6?: number;
            NewRead_Num7?: number;
            NewRead_Num8?: number;
            NewRead_Num9?: number;
            NewRead_Text1?: string;
            NewRead_Text10?: string;
            NewRead_Text11?: string;
            NewRead_Text12?: string;
            NewRead_Text13?: string;
            NewRead_Text14?: string;
            NewRead_Text15?: string;
            NewRead_Text16?: string;
            NewRead_Text17?: string;
            NewRead_Text18?: string;
            NewRead_Text19?: string;
            NewRead_Text2?: string;
            NewRead_Text20?: string;
            NewRead_Text3?: string;
            NewRead_Text4?: string;
            NewRead_Text5?: string;
            NewRead_Text6?: string;
            NewRead_Text7?: string;
            NewRead_Text8?: string;
            NewRead_Text9?: string;
            NewUid?: string;
            OldRead_Date1?: Date;
            OldRead_Date2?: Date;
            OldRead_Date3?: Date;
            OldRead_Date4?: Date;
            OldRead_Date5?: Date;
            OldRead_Id?: number;
            OldRead_Num1?: number;
            OldRead_Num10?: number;
            OldRead_Num11?: number;
            OldRead_Num12?: number;
            OldRead_Num13?: number;
            OldRead_Num14?: number;
            OldRead_Num15?: number;
            OldRead_Num16?: number;
            OldRead_Num17?: number;
            OldRead_Num18?: number;
            OldRead_Num19?: number;
            OldRead_Num2?: number;
            OldRead_Num20?: number;
            OldRead_Num3?: number;
            OldRead_Num4?: number;
            OldRead_Num5?: number;
            OldRead_Num6?: number;
            OldRead_Num7?: number;
            OldRead_Num8?: number;
            OldRead_Num9?: number;
            OldRead_Text1?: string;
            OldRead_Text10?: string;
            OldRead_Text11?: string;
            OldRead_Text12?: string;
            OldRead_Text13?: string;
            OldRead_Text14?: string;
            OldRead_Text15?: string;
            OldRead_Text16?: string;
            OldRead_Text17?: string;
            OldRead_Text18?: string;
            OldRead_Text19?: string;
            OldRead_Text2?: string;
            OldRead_Text20?: string;
            OldRead_Text3?: string;
            OldRead_Text4?: string;
            OldRead_Text5?: string;
            OldRead_Text6?: string;
            OldRead_Text7?: string;
            OldRead_Text8?: string;
            OldRead_Text9?: string;
            OldUid?: string;
            OperationComments?: string;
            OperationId: number;
            RecordDate?: Date;
        }
    }
    namespace Responses {
        interface AddChangeOutRead extends ServiceTypes.CoreResponseBase_<ChangeOutRead> {
        }
        interface AddOperation extends ServiceTypes.CoreResponseBase_<ChangeOutOperation> {
        }
        interface Attach extends ServiceTypes.CoreResponseBase_<EquipChangeOut> {
        }
        interface ById extends ServiceTypes.CoreResponseBase_<EquipChangeOut> {
        }
        interface ByIds extends ServiceTypes.CoreResponseBase_<EquipChangeOutBase[]> {
        }
        interface Delete extends ServiceTypes.CoreResponseBase_<{
            [key: number]: boolean;
        }> {
        }
        interface DeleteChangeOutReads extends ServiceTypes.CoreResponseBase_<{
            [key: number]: boolean;
        }> {
        }
        interface DeleteOperations extends ServiceTypes.CoreResponseBase_<{
            [key: number]: boolean;
        }> {
        }
        interface Detach extends ServiceTypes.CoreResponseBase_<EquipChangeOut> {
        }
        interface DirectParent extends ServiceTypes.CoreResponseBase_<ParentChildItem> {
        }
        interface Entities extends ServiceTypes.CoreResponseBase_<WorkOrderEntity[]> {
        }
        interface Entity extends ServiceTypes.CoreResponseBase_<WorkOrderEntity> {
        }
        interface History extends ServiceTypes.CoreResponseBase_<EquipmentChangeOutHistory> {
        }
        interface Read extends ServiceTypes.CoreResponseBase_<EquipChangeOut> {
        }
        interface ReadConfigs extends ServiceTypes.CoreResponseBase_<ChgOutReadConfig[]> {
        }
        interface Related extends ServiceTypes.CoreResponseBase_<WorkOrderEntity[]> {
        }
        interface Replace extends ServiceTypes.CoreResponseBase_<EquipChangeOut> {
        }
        interface UpdateChangeOutRead extends ServiceTypes.CoreResponseBase_<ChangeOutRead> {
        }
        interface UpdateOperation extends ServiceTypes.CoreResponseBase_<ChangeOutOperation> {
        }
    }
    interface IEquipmentChangeOutService {
        AddChangeOutRead?: (request: Requests.AddChangeOutRead) => Promise<Responses.AddChangeOutRead>;
        AddOperation?: (request: Requests.AddOperation) => Promise<Responses.AddOperation>;
        Attach?: (request: Requests.Attach) => Promise<Responses.Attach>;
        ById?: (request: Requests.ById) => Promise<Responses.ById>;
        ByIds?: (request: Requests.ByIds) => Promise<Responses.ByIds>;
        Delete?: (request: Requests.Delete) => Promise<Responses.Delete>;
        DeleteChangeOutReads?: (request: Requests.DeleteChangeOutReads) => Promise<Responses.DeleteChangeOutReads>;
        DeleteOperations?: (request: Requests.DeleteOperations) => Promise<Responses.DeleteOperations>;
        Detach?: (request: Requests.Detach) => Promise<Responses.Detach>;
        DirectParent?: (request: Requests.DirectParent) => Promise<Responses.DirectParent>;
        Entities?: (request: Requests.Entities) => Promise<Responses.Entities>;
        Entity?: (request: Requests.Entity) => Promise<Responses.Entity>;
        History?: (request: Requests.History) => Promise<Responses.History>;
        Read?: (request: Requests.Read) => Promise<Responses.Read>;
        ReadConfigs?: (request: Requests.ReadConfigs) => Promise<Responses.ReadConfigs>;
        Related?: (request: Requests.Related) => Promise<Responses.Related>;
        Replace?: (request: Requests.Replace) => Promise<Responses.Replace>;
        UpdateChangeOutRead?: (request: Requests.UpdateChangeOutRead) => Promise<Responses.UpdateChangeOutRead>;
        UpdateOperation?: (request: Requests.UpdateOperation) => Promise<Responses.UpdateOperation>;
    }
}
