import { TvInspectionFieldUnits } from '../core/types/TvInspectionFieldUnits';
import { CodeDescScore } from '../core/types/CodeDescScore';
import { CodeDesc } from '../core/types/CodeDesc';
import { RelEmpToField } from '../core/types/RelEmpToField';
import { WorkOrderEntity } from '../core/types/WorkOrderEntity';
import { TvInspectionDescScores } from '../core/types/TvInspectionDescScores';
import { SearchDefinition } from '../core/types/SearchDefinition';
import { TvInspectionCodeDescs } from '../core/types/TvInspectionCodeDescs';
import { TvInspectionBase } from '../core/types/TvInspectionBase';
import { CctvCodeDescGrade } from '../core/types/CctvCodeDescGrade';
import { TvInspection } from '../core/types/TvInspection';
import { TvObservation } from '../core/types/TvObservation';
import { ServiceTypes } from '../core/service-types';
export declare namespace TvInspectionServiceTypes {
    namespace Requests {
        interface AddObservation extends ServiceTypes.CoreRequestBase {
            Cause?: number;
            CctvCode?: string;
            ClockTo?: number;
            Continuous?: string;
            DistFromDown?: number;
            DistFromUp?: number;
            Grade?: number;
            Joint?: string;
            ObservDesc?: string;
            ObservDescScore?: number;
            ObservPos?: string;
            ObservRemarks?: string;
            ObservType?: string;
            TapeRead?: string;
            TvId: number;
            TvImage?: string;
            TvTape?: string;
            ValueDimension1?: number;
            ValueDimension2?: number;
            ValuePercent?: number;
            VCR_Time?: string;
        }
        interface ById extends ServiceTypes.CoreRequestBase {
            TvId: number;
        }
        interface ByIds extends ServiceTypes.CoreRequestBase {
            TvIds: number[];
        }
        interface ByWorkOrder extends ServiceTypes.CoreRequestBase {
            WorkOrderIds?: string[];
        }
        interface CctvObservationCodeTypes extends ServiceTypes.CoreRequestBase {
        }
        interface ChangeCustomFieldCategory extends ServiceTypes.CoreRequestBase {
            CategoryId: number;
            TvIds: number[];
        }
        interface CodeDescriptions extends ServiceTypes.CoreRequestBase {
            PipeType: string;
        }
        interface ConfirmDyeLeaks extends ServiceTypes.CoreRequestBase {
            PipeLeakIds?: number[];
            TvConfirmed?: boolean;
            TvId: number;
        }
        interface ConfirmSmokeTests extends ServiceTypes.CoreRequestBase {
            PipeLeakIds?: number[];
            TvConfirmed?: boolean;
            TvId: number;
        }
        interface Create extends ServiceTypes.CoreRequestBase {
            CertificateNumber?: string;
            City?: string;
            Coating_Method?: string;
            CondRating?: number;
            Consequence_Of_Failure?: string;
            CounterStart?: string;
            CounterStop?: string;
            Customer?: string;
            CustomFieldValues?: {
                [key: number]: string;
            };
            Date1?: Date;
            Date2?: Date;
            Date3?: Date;
            Date4?: Date;
            Date5?: Date;
            DateCleaned?: Date;
            Deterioration?: string;
            DeterScore?: number;
            Diameter?: number;
            Down_Easting?: string;
            Down_Elevation?: string;
            Down_Northing?: string;
            DownLocation?: string;
            DownMh?: string;
            DownType?: string;
            DrainageArea?: string;
            DwnDepth?: number;
            DyeId?: number;
            FlowControl?: string;
            FlowDepth?: number;
            ForemanRecomnd?: string;
            GPS_Accuracy?: string;
            GroundCond?: string;
            GroundCondScore?: number;
            HydRating?: number;
            InitiatedByApp?: string;
            InspCustFieldCatId?: number;
            InspectedBySid?: number;
            Inspection_Status?: string;
            Inspection_Technology_Used?: string;
            IsImperial?: boolean;
            JointLength?: number;
            JointType?: string;
            LiningMethod?: string;
            Location?: string;
            Location_Code?: string;
            Location_Details?: string;
            MapNumber?: string;
            MasterTapeNum?: string;
            Material?: string;
            MH_Coordinate_System?: string;
            Num1?: number;
            Num2?: number;
            Num3?: number;
            Num4?: number;
            Num5?: number;
            ObservationSum?: string;
            ObservMethod?: number;
            OmRating?: number;
            Owner?: string;
            PipeId: string;
            PipeLength?: number;
            PipeType: string;
            PoNumber?: string;
            PrecipType?: string;
            PrecipTypeScore?: number;
            PreCleaning?: string;
            Pressure_Value?: number;
            Project?: string;
            RehabStatus?: string;
            RepairsMade?: string;
            Reverse_Setup_Flag?: number;
            ReverseSetup?: boolean;
            ReviewedBySid?: number;
            Reviewer_Certificate_Number?: string;
            RimToGradeD?: number;
            RimToGradeU?: number;
            RimToInvertD?: number;
            RimToInvertU?: number;
            RootRating?: number;
            SewerCategory?: string;
            SewerUse?: string;
            Shape?: string;
            SmokeId?: number;
            Spot?: string;
            SpotScore?: number;
            Street?: string;
            StructRating?: number;
            SuperAprvlComnts?: string;
            SurfaceType?: string;
            TapeLibraryNum?: string;
            Text1?: string;
            Text10?: string;
            Text2?: string;
            Text3?: string;
            Text4?: string;
            Text5?: string;
            Text6?: string;
            Text7?: string;
            Text8?: string;
            Text9?: string;
            TotalLength?: number;
            TvDate?: Date;
            TvObservations?: TvObservation[];
            TvReason?: string;
            Up_Easting?: string;
            Up_Elevation?: string;
            Up_Northing?: string;
            UpdateGis?: boolean;
            UpdateMap?: boolean;
            UpDepth?: number;
            UpLocation?: string;
            UpMh?: string;
            UpType?: string;
            Vertical_Datum?: string;
            VideoLocation?: string;
            VideoTapeNum?: string;
            VtrFormat?: string;
            Weather?: string;
            Width?: number;
            WorkOrderId: string;
            YearLaid?: number;
            YearRenewed?: number;
        }
        interface CreateFromPacp extends ServiceTypes.CoreRequestBase {
            CertificateNumber?: string;
            City?: string;
            Coating_Method?: string;
            CondRating?: number;
            Consequence_Of_Failure?: string;
            CounterStart?: string;
            CounterStop?: string;
            Customer?: string;
            CustomFieldValues?: {
                [key: number]: string;
            };
            Date1?: Date;
            Date2?: Date;
            Date3?: Date;
            Date4?: Date;
            Date5?: Date;
            DateCleaned?: Date;
            Deterioration?: string;
            DeterScore?: number;
            Diameter?: number;
            Down_Easting?: string;
            Down_Elevation?: string;
            Down_Northing?: string;
            DownLocation?: string;
            DownMh?: string;
            DownType?: string;
            DrainageArea?: string;
            DwnDepth?: number;
            DyeId?: number;
            FlowControl?: string;
            FlowDepth?: number;
            ForemanRecomnd?: string;
            GPS_Accuracy?: string;
            GroundCond?: string;
            GroundCondScore?: number;
            HydRating?: number;
            InitiatedByApp?: string;
            InspCustFieldCatId?: number;
            InspectedBySid?: number;
            Inspection_Status?: string;
            Inspection_Technology_Used?: string;
            IsImperial?: boolean;
            JointLength?: number;
            JointType?: string;
            LiningMethod?: string;
            Location?: string;
            Location_Code?: string;
            Location_Details?: string;
            MapNumber?: string;
            MasterTapeNum?: string;
            Material?: string;
            MH_Coordinate_System?: string;
            Num1?: number;
            Num2?: number;
            Num3?: number;
            Num4?: number;
            Num5?: number;
            ObservationSum?: string;
            ObservMethod?: number;
            OmRating?: number;
            Owner?: string;
            PipeId: string;
            PipeLength?: number;
            PipeType: string;
            PoNumber?: string;
            PrecipType?: string;
            PrecipTypeScore?: number;
            PreCleaning?: string;
            Pressure_Value?: number;
            Project?: string;
            RehabStatus?: string;
            RepairsMade?: string;
            Reverse_Setup_Flag?: number;
            ReverseSetup?: boolean;
            ReviewedBySid?: number;
            Reviewer_Certificate_Number?: string;
            RimToGradeD?: number;
            RimToGradeU?: number;
            RimToInvertD?: number;
            RimToInvertU?: number;
            RootRating?: number;
            SewerCategory?: string;
            SewerUse?: string;
            Shape?: string;
            SmokeId?: number;
            Spot?: string;
            SpotScore?: number;
            Street?: string;
            StructRating?: number;
            SuperAprvlComnts?: string;
            SurfaceType?: string;
            TapeLibraryNum?: string;
            Text1?: string;
            Text10?: string;
            Text2?: string;
            Text3?: string;
            Text4?: string;
            Text5?: string;
            Text6?: string;
            Text7?: string;
            Text8?: string;
            Text9?: string;
            TotalLength?: number;
            TvDate?: Date;
            TvObservations?: TvObservation[];
            TvReason?: string;
            Up_Easting?: string;
            Up_Elevation?: string;
            Up_Northing?: string;
            UpdateGis?: boolean;
            UpdateMap?: boolean;
            UpDepth?: number;
            UpLocation?: string;
            UpMh?: string;
            UpType?: string;
            Vertical_Datum?: string;
            VideoLocation?: string;
            VideoTapeNum?: string;
            VtrFormat?: string;
            Weather?: string;
            Width?: number;
            WorkOrderId: string;
            YearLaid?: number;
            YearRenewed?: number;
        }
        interface CreateSearchDefinition extends ServiceTypes.CoreRequestBase {
            CertificateNumber?: string[];
            City?: string[];
            Coating_Method?: string[];
            CondRatingIncludeNulls?: boolean;
            CondRatingIsMaxValueExclusive?: boolean;
            CondRatingIsMinValueExclusive?: boolean;
            CondRatingMaxValue?: number;
            CondRatingMinValue?: number;
            CondRatingRangeType?: number;
            CondRatingValues?: number[];
            Consequence_Of_Failure?: string[];
            CounterStart?: string[];
            CounterStop?: string[];
            Customer?: string[];
            Date1Begin?: Date;
            Date1End?: Date;
            Date1IsNull?: boolean;
            Date1NotInRange?: boolean;
            Date1RangeIncludeCurrent?: boolean;
            Date1RangeLast?: number;
            Date1RangeNext?: number;
            Date1RangeUnits?: number;
            Date2Begin?: Date;
            Date2End?: Date;
            Date2IsNull?: boolean;
            Date2NotInRange?: boolean;
            Date2RangeIncludeCurrent?: boolean;
            Date2RangeLast?: number;
            Date2RangeNext?: number;
            Date2RangeUnits?: number;
            Date3Begin?: Date;
            Date3End?: Date;
            Date3IsNull?: boolean;
            Date3NotInRange?: boolean;
            Date3RangeIncludeCurrent?: boolean;
            Date3RangeLast?: number;
            Date3RangeNext?: number;
            Date3RangeUnits?: number;
            Date4Begin?: Date;
            Date4End?: Date;
            Date4IsNull?: boolean;
            Date4NotInRange?: boolean;
            Date4RangeIncludeCurrent?: boolean;
            Date4RangeLast?: number;
            Date4RangeNext?: number;
            Date4RangeUnits?: number;
            Date5Begin?: Date;
            Date5End?: Date;
            Date5IsNull?: boolean;
            Date5NotInRange?: boolean;
            Date5RangeIncludeCurrent?: boolean;
            Date5RangeLast?: number;
            Date5RangeNext?: number;
            Date5RangeUnits?: number;
            DateCleanedBegin?: Date;
            DateCleanedEnd?: Date;
            DateCleanedIsNull?: boolean;
            DateCleanedNotInRange?: boolean;
            DateCleanedRangeIncludeCurrent?: boolean;
            DateCleanedRangeLast?: number;
            DateCleanedRangeNext?: number;
            DateCleanedRangeUnits?: number;
            Deterioration?: string[];
            DeterScoreIncludeNulls?: boolean;
            DeterScoreIsMaxValueExclusive?: boolean;
            DeterScoreIsMinValueExclusive?: boolean;
            DeterScoreMaxValue?: number;
            DeterScoreMinValue?: number;
            DeterScoreRangeType?: number;
            DeterScoreValues?: number[];
            DiameterIncludeNulls?: boolean;
            DiameterIsMaxValueExclusive?: boolean;
            DiameterIsMinValueExclusive?: boolean;
            DiameterMaxValue?: number;
            DiameterMinValue?: number;
            DiameterRangeType?: number;
            DiameterValues?: number[];
            Down_Easting?: string[];
            Down_Elevation?: string[];
            Down_Northing?: string[];
            DownLocation?: string[];
            DownMh?: string[];
            DownType?: string[];
            DrainageArea?: string[];
            DwnDepthIncludeNulls?: boolean;
            DwnDepthIsMaxValueExclusive?: boolean;
            DwnDepthIsMinValueExclusive?: boolean;
            DwnDepthMaxValue?: number;
            DwnDepthMinValue?: number;
            DwnDepthRangeType?: number;
            DwnDepthValues?: number[];
            DyeId?: number[];
            DyeIdIsInList?: boolean;
            FlowControl?: string[];
            FlowDepthIncludeNulls?: boolean;
            FlowDepthIsMaxValueExclusive?: boolean;
            FlowDepthIsMinValueExclusive?: boolean;
            FlowDepthMaxValue?: number;
            FlowDepthMinValue?: number;
            FlowDepthRangeType?: number;
            FlowDepthValues?: number[];
            ForemanRecomnd?: string[];
            GPS_Accuracy?: string[];
            GroundCond?: string[];
            GroundCondScoreIncludeNulls?: boolean;
            GroundCondScoreIsMaxValueExclusive?: boolean;
            GroundCondScoreIsMinValueExclusive?: boolean;
            GroundCondScoreMaxValue?: number;
            GroundCondScoreMinValue?: number;
            GroundCondScoreRangeType?: number;
            GroundCondScoreValues?: number[];
            HydRatingIncludeNulls?: boolean;
            HydRatingIsMaxValueExclusive?: boolean;
            HydRatingIsMinValueExclusive?: boolean;
            HydRatingMaxValue?: number;
            HydRatingMinValue?: number;
            HydRatingRangeType?: number;
            HydRatingValues?: number[];
            InitiatedByApp?: string[];
            InspCustFieldCatId?: number[];
            InspCustFieldCatIdIsInList?: boolean;
            InspectedBy?: string[];
            InspectedBySid?: number[];
            InspectedBySidIsInList?: boolean;
            Inspection_Status?: string[];
            Inspection_Technology_Used?: string[];
            IsImperial?: boolean;
            JointLengthIncludeNulls?: boolean;
            JointLengthIsMaxValueExclusive?: boolean;
            JointLengthIsMinValueExclusive?: boolean;
            JointLengthMaxValue?: number;
            JointLengthMinValue?: number;
            JointLengthRangeType?: number;
            JointLengthValues?: number[];
            JointType?: string[];
            LiningMethod?: string[];
            Location?: string[];
            Location_Code?: string[];
            Location_Details?: string[];
            MapNumber?: string[];
            MasterTapeNum?: string[];
            Material?: string[];
            MaxResults?: number;
            MH_Coordinate_System?: string[];
            Num1IncludeNulls?: boolean;
            Num1IsMaxValueExclusive?: boolean;
            Num1IsMinValueExclusive?: boolean;
            Num1MaxValue?: number;
            Num1MinValue?: number;
            Num1RangeType?: number;
            Num1Values?: number[];
            Num2IncludeNulls?: boolean;
            Num2IsMaxValueExclusive?: boolean;
            Num2IsMinValueExclusive?: boolean;
            Num2MaxValue?: number;
            Num2MinValue?: number;
            Num2RangeType?: number;
            Num2Values?: number[];
            Num3IncludeNulls?: boolean;
            Num3IsMaxValueExclusive?: boolean;
            Num3IsMinValueExclusive?: boolean;
            Num3MaxValue?: number;
            Num3MinValue?: number;
            Num3RangeType?: number;
            Num3Values?: number[];
            Num4IncludeNulls?: boolean;
            Num4IsMaxValueExclusive?: boolean;
            Num4IsMinValueExclusive?: boolean;
            Num4MaxValue?: number;
            Num4MinValue?: number;
            Num4RangeType?: number;
            Num4Values?: number[];
            Num5IncludeNulls?: boolean;
            Num5IsMaxValueExclusive?: boolean;
            Num5IsMinValueExclusive?: boolean;
            Num5MaxValue?: number;
            Num5MinValue?: number;
            Num5RangeType?: number;
            Num5Values?: number[];
            ObservationSum?: string[];
            ObservMethod?: number;
            OmRatingIncludeNulls?: boolean;
            OmRatingIsMaxValueExclusive?: boolean;
            OmRatingIsMinValueExclusive?: boolean;
            OmRatingMaxValue?: number;
            OmRatingMinValue?: number;
            OmRatingRangeType?: number;
            OmRatingValues?: number[];
            Owner?: string[];
            PipeId?: string[];
            PipeLengthIncludeNulls?: boolean;
            PipeLengthIsMaxValueExclusive?: boolean;
            PipeLengthIsMinValueExclusive?: boolean;
            PipeLengthMaxValue?: number;
            PipeLengthMinValue?: number;
            PipeLengthRangeType?: number;
            PipeLengthValues?: number[];
            PipeType?: string[];
            PoNumber?: string[];
            PrecipType?: string[];
            PrecipTypeScoreIncludeNulls?: boolean;
            PrecipTypeScoreIsMaxValueExclusive?: boolean;
            PrecipTypeScoreIsMinValueExclusive?: boolean;
            PrecipTypeScoreMaxValue?: number;
            PrecipTypeScoreMinValue?: number;
            PrecipTypeScoreRangeType?: number;
            PrecipTypeScoreValues?: number[];
            PreCleaning?: string[];
            Pressure_ValueIncludeNulls?: boolean;
            Pressure_ValueIsMaxValueExclusive?: boolean;
            Pressure_ValueIsMinValueExclusive?: boolean;
            Pressure_ValueMaxValue?: number;
            Pressure_ValueMinValue?: number;
            Pressure_ValueRangeType?: number;
            Pressure_ValueValues?: number[];
            Project?: string[];
            RehabStatus?: string[];
            RepairsMade?: string[];
            Reverse_Setup_FlagIncludeNulls?: boolean;
            Reverse_Setup_FlagIsMaxValueExclusive?: boolean;
            Reverse_Setup_FlagIsMinValueExclusive?: boolean;
            Reverse_Setup_FlagMaxValue?: number;
            Reverse_Setup_FlagMinValue?: number;
            Reverse_Setup_FlagRangeType?: number;
            Reverse_Setup_FlagValues?: number[];
            ReverseSetup?: boolean;
            ReviewedBySid?: number[];
            ReviewedBySidIsInList?: boolean;
            Reviewer_Certificate_Number?: string[];
            RimToGradeDIncludeNulls?: boolean;
            RimToGradeDIsMaxValueExclusive?: boolean;
            RimToGradeDIsMinValueExclusive?: boolean;
            RimToGradeDMaxValue?: number;
            RimToGradeDMinValue?: number;
            RimToGradeDRangeType?: number;
            RimToGradeDValues?: number[];
            RimToGradeUIncludeNulls?: boolean;
            RimToGradeUIsMaxValueExclusive?: boolean;
            RimToGradeUIsMinValueExclusive?: boolean;
            RimToGradeUMaxValue?: number;
            RimToGradeUMinValue?: number;
            RimToGradeURangeType?: number;
            RimToGradeUValues?: number[];
            RimToInvertDIncludeNulls?: boolean;
            RimToInvertDIsMaxValueExclusive?: boolean;
            RimToInvertDIsMinValueExclusive?: boolean;
            RimToInvertDMaxValue?: number;
            RimToInvertDMinValue?: number;
            RimToInvertDRangeType?: number;
            RimToInvertDValues?: number[];
            RimToInvertUIncludeNulls?: boolean;
            RimToInvertUIsMaxValueExclusive?: boolean;
            RimToInvertUIsMinValueExclusive?: boolean;
            RimToInvertUMaxValue?: number;
            RimToInvertUMinValue?: number;
            RimToInvertURangeType?: number;
            RimToInvertUValues?: number[];
            RootRatingIncludeNulls?: boolean;
            RootRatingIsMaxValueExclusive?: boolean;
            RootRatingIsMinValueExclusive?: boolean;
            RootRatingMaxValue?: number;
            RootRatingMinValue?: number;
            RootRatingRangeType?: number;
            RootRatingValues?: number[];
            SaveDefinition?: boolean;
            SearchName?: string;
            SewerCategory?: string[];
            SewerUse?: string[];
            Shape?: string[];
            SharedWithin?: number;
            SmokeId?: number[];
            SmokeIdIsInList?: boolean;
            Spot?: string[];
            SpotScoreIncludeNulls?: boolean;
            SpotScoreIsMaxValueExclusive?: boolean;
            SpotScoreIsMinValueExclusive?: boolean;
            SpotScoreMaxValue?: number;
            SpotScoreMinValue?: number;
            SpotScoreRangeType?: number;
            SpotScoreValues?: number[];
            Street?: string[];
            StructRatingIncludeNulls?: boolean;
            StructRatingIsMaxValueExclusive?: boolean;
            StructRatingIsMinValueExclusive?: boolean;
            StructRatingMaxValue?: number;
            StructRatingMinValue?: number;
            StructRatingRangeType?: number;
            StructRatingValues?: number[];
            SuperAprvlComnts?: string[];
            SurfaceType?: string[];
            TapeLibraryNum?: string[];
            Text1?: string[];
            Text10?: string[];
            Text2?: string[];
            Text3?: string[];
            Text4?: string[];
            Text5?: string[];
            Text6?: string[];
            Text7?: string[];
            Text8?: string[];
            Text9?: string[];
            TotalLengthIncludeNulls?: boolean;
            TotalLengthIsMaxValueExclusive?: boolean;
            TotalLengthIsMinValueExclusive?: boolean;
            TotalLengthMaxValue?: number;
            TotalLengthMinValue?: number;
            TotalLengthRangeType?: number;
            TotalLengthValues?: number[];
            TvDateBegin?: Date;
            TvDateEnd?: Date;
            TvDateIsNull?: boolean;
            TvDateNotInRange?: boolean;
            TvDateRangeIncludeCurrent?: boolean;
            TvDateRangeLast?: number;
            TvDateRangeNext?: number;
            TvDateRangeUnits?: number;
            TvId?: number[];
            TvIdIsInList?: boolean;
            TvReason?: string[];
            Up_Easting?: string[];
            Up_Elevation?: string[];
            Up_Northing?: string[];
            UpdateMap?: boolean;
            UpDepthIncludeNulls?: boolean;
            UpDepthIsMaxValueExclusive?: boolean;
            UpDepthIsMinValueExclusive?: boolean;
            UpDepthMaxValue?: number;
            UpDepthMinValue?: number;
            UpDepthRangeType?: number;
            UpDepthValues?: number[];
            UpLocation?: string[];
            UpMh?: string[];
            UpType?: string[];
            Vertical_Datum?: string[];
            VideoLocation?: string[];
            VideoTapeNum?: string[];
            VtrFormat?: string[];
            Weather?: string[];
            WidthIncludeNulls?: boolean;
            WidthIsMaxValueExclusive?: boolean;
            WidthIsMinValueExclusive?: boolean;
            WidthMaxValue?: number;
            WidthMinValue?: number;
            WidthRangeType?: number;
            WidthValues?: number[];
            WorkOrderId?: string[];
            XIncludeNulls?: boolean;
            XIsMaxValueExclusive?: boolean;
            XIsMinValueExclusive?: boolean;
            XMaxValue?: number;
            XMinValue?: number;
            XRangeType?: number;
            XValues?: number[];
            YearLaidIncludeNulls?: boolean;
            YearLaidIsMaxValueExclusive?: boolean;
            YearLaidIsMinValueExclusive?: boolean;
            YearLaidMaxValue?: number;
            YearLaidMinValue?: number;
            YearLaidRangeType?: number;
            YearLaidValues?: number[];
            YearRenewedIncludeNulls?: boolean;
            YearRenewedIsMaxValueExclusive?: boolean;
            YearRenewedIsMinValueExclusive?: boolean;
            YearRenewedMaxValue?: number;
            YearRenewedMinValue?: number;
            YearRenewedRangeType?: number;
            YearRenewedValues?: number[];
            YIncludeNulls?: boolean;
            YIsMaxValueExclusive?: boolean;
            YIsMinValueExclusive?: boolean;
            YMaxValue?: number;
            YMinValue?: number;
            YRangeType?: number;
            YValues?: number[];
        }
        interface DescriptionScores extends ServiceTypes.CoreRequestBase {
        }
        interface DownstreamNode extends ServiceTypes.CoreRequestBase {
            EntityType: string;
            EntityUid: string;
        }
        interface InspectedBy extends ServiceTypes.CoreRequestBase {
            DomainId?: number;
            TvId?: number;
        }
        interface Observation extends ServiceTypes.CoreRequestBase {
            ObservationId?: number;
        }
        interface ObservationCauseCodeDescriptions extends ServiceTypes.CoreRequestBase {
            ObservationMethod?: number;
        }
        interface ObservationCodeTypes extends ServiceTypes.CoreRequestBase {
        }
        interface Observations extends ServiceTypes.CoreRequestBase {
            TvIds?: number[];
        }
        interface ReviewedBy extends ServiceTypes.CoreRequestBase {
            DomainId?: number;
            TvId?: number;
        }
        interface Search extends ServiceTypes.CoreRequestBase {
            CertificateNumber?: string[];
            City?: string[];
            Coating_Method?: string[];
            CondRatingIncludeNulls?: boolean;
            CondRatingIsMaxValueExclusive?: boolean;
            CondRatingIsMinValueExclusive?: boolean;
            CondRatingMaxValue?: number;
            CondRatingMinValue?: number;
            CondRatingRangeType?: number;
            CondRatingValues?: number[];
            Consequence_Of_Failure?: string[];
            CounterStart?: string[];
            CounterStop?: string[];
            Customer?: string[];
            Date1Begin?: Date;
            Date1End?: Date;
            Date1IsNull?: boolean;
            Date1NotInRange?: boolean;
            Date1RangeIncludeCurrent?: boolean;
            Date1RangeLast?: number;
            Date1RangeNext?: number;
            Date1RangeUnits?: number;
            Date2Begin?: Date;
            Date2End?: Date;
            Date2IsNull?: boolean;
            Date2NotInRange?: boolean;
            Date2RangeIncludeCurrent?: boolean;
            Date2RangeLast?: number;
            Date2RangeNext?: number;
            Date2RangeUnits?: number;
            Date3Begin?: Date;
            Date3End?: Date;
            Date3IsNull?: boolean;
            Date3NotInRange?: boolean;
            Date3RangeIncludeCurrent?: boolean;
            Date3RangeLast?: number;
            Date3RangeNext?: number;
            Date3RangeUnits?: number;
            Date4Begin?: Date;
            Date4End?: Date;
            Date4IsNull?: boolean;
            Date4NotInRange?: boolean;
            Date4RangeIncludeCurrent?: boolean;
            Date4RangeLast?: number;
            Date4RangeNext?: number;
            Date4RangeUnits?: number;
            Date5Begin?: Date;
            Date5End?: Date;
            Date5IsNull?: boolean;
            Date5NotInRange?: boolean;
            Date5RangeIncludeCurrent?: boolean;
            Date5RangeLast?: number;
            Date5RangeNext?: number;
            Date5RangeUnits?: number;
            DateCleanedBegin?: Date;
            DateCleanedEnd?: Date;
            DateCleanedIsNull?: boolean;
            DateCleanedNotInRange?: boolean;
            DateCleanedRangeIncludeCurrent?: boolean;
            DateCleanedRangeLast?: number;
            DateCleanedRangeNext?: number;
            DateCleanedRangeUnits?: number;
            Deterioration?: string[];
            DeterScoreIncludeNulls?: boolean;
            DeterScoreIsMaxValueExclusive?: boolean;
            DeterScoreIsMinValueExclusive?: boolean;
            DeterScoreMaxValue?: number;
            DeterScoreMinValue?: number;
            DeterScoreRangeType?: number;
            DeterScoreValues?: number[];
            DiameterIncludeNulls?: boolean;
            DiameterIsMaxValueExclusive?: boolean;
            DiameterIsMinValueExclusive?: boolean;
            DiameterMaxValue?: number;
            DiameterMinValue?: number;
            DiameterRangeType?: number;
            DiameterValues?: number[];
            Down_Easting?: string[];
            Down_Elevation?: string[];
            Down_Northing?: string[];
            DownLocation?: string[];
            DownMh?: string[];
            DownType?: string[];
            DrainageArea?: string[];
            DwnDepthIncludeNulls?: boolean;
            DwnDepthIsMaxValueExclusive?: boolean;
            DwnDepthIsMinValueExclusive?: boolean;
            DwnDepthMaxValue?: number;
            DwnDepthMinValue?: number;
            DwnDepthRangeType?: number;
            DwnDepthValues?: number[];
            DyeId?: number[];
            DyeIdIsInList?: boolean;
            FlowControl?: string[];
            FlowDepthIncludeNulls?: boolean;
            FlowDepthIsMaxValueExclusive?: boolean;
            FlowDepthIsMinValueExclusive?: boolean;
            FlowDepthMaxValue?: number;
            FlowDepthMinValue?: number;
            FlowDepthRangeType?: number;
            FlowDepthValues?: number[];
            ForemanRecomnd?: string[];
            GPS_Accuracy?: string[];
            GroundCond?: string[];
            GroundCondScoreIncludeNulls?: boolean;
            GroundCondScoreIsMaxValueExclusive?: boolean;
            GroundCondScoreIsMinValueExclusive?: boolean;
            GroundCondScoreMaxValue?: number;
            GroundCondScoreMinValue?: number;
            GroundCondScoreRangeType?: number;
            GroundCondScoreValues?: number[];
            HydRatingIncludeNulls?: boolean;
            HydRatingIsMaxValueExclusive?: boolean;
            HydRatingIsMinValueExclusive?: boolean;
            HydRatingMaxValue?: number;
            HydRatingMinValue?: number;
            HydRatingRangeType?: number;
            HydRatingValues?: number[];
            InitiatedByApp?: string[];
            InspCustFieldCatId?: number[];
            InspCustFieldCatIdIsInList?: boolean;
            InspectedBy?: string[];
            InspectedBySid?: number[];
            InspectedBySidIsInList?: boolean;
            Inspection_Status?: string[];
            Inspection_Technology_Used?: string[];
            IsImperial?: boolean;
            JointLengthIncludeNulls?: boolean;
            JointLengthIsMaxValueExclusive?: boolean;
            JointLengthIsMinValueExclusive?: boolean;
            JointLengthMaxValue?: number;
            JointLengthMinValue?: number;
            JointLengthRangeType?: number;
            JointLengthValues?: number[];
            JointType?: string[];
            LiningMethod?: string[];
            Location?: string[];
            Location_Code?: string[];
            Location_Details?: string[];
            MapNumber?: string[];
            MasterTapeNum?: string[];
            Material?: string[];
            MaxResults?: number;
            MH_Coordinate_System?: string[];
            Num1IncludeNulls?: boolean;
            Num1IsMaxValueExclusive?: boolean;
            Num1IsMinValueExclusive?: boolean;
            Num1MaxValue?: number;
            Num1MinValue?: number;
            Num1RangeType?: number;
            Num1Values?: number[];
            Num2IncludeNulls?: boolean;
            Num2IsMaxValueExclusive?: boolean;
            Num2IsMinValueExclusive?: boolean;
            Num2MaxValue?: number;
            Num2MinValue?: number;
            Num2RangeType?: number;
            Num2Values?: number[];
            Num3IncludeNulls?: boolean;
            Num3IsMaxValueExclusive?: boolean;
            Num3IsMinValueExclusive?: boolean;
            Num3MaxValue?: number;
            Num3MinValue?: number;
            Num3RangeType?: number;
            Num3Values?: number[];
            Num4IncludeNulls?: boolean;
            Num4IsMaxValueExclusive?: boolean;
            Num4IsMinValueExclusive?: boolean;
            Num4MaxValue?: number;
            Num4MinValue?: number;
            Num4RangeType?: number;
            Num4Values?: number[];
            Num5IncludeNulls?: boolean;
            Num5IsMaxValueExclusive?: boolean;
            Num5IsMinValueExclusive?: boolean;
            Num5MaxValue?: number;
            Num5MinValue?: number;
            Num5RangeType?: number;
            Num5Values?: number[];
            ObservationSum?: string[];
            ObservMethod?: number;
            OmRatingIncludeNulls?: boolean;
            OmRatingIsMaxValueExclusive?: boolean;
            OmRatingIsMinValueExclusive?: boolean;
            OmRatingMaxValue?: number;
            OmRatingMinValue?: number;
            OmRatingRangeType?: number;
            OmRatingValues?: number[];
            Owner?: string[];
            PipeId?: string[];
            PipeLengthIncludeNulls?: boolean;
            PipeLengthIsMaxValueExclusive?: boolean;
            PipeLengthIsMinValueExclusive?: boolean;
            PipeLengthMaxValue?: number;
            PipeLengthMinValue?: number;
            PipeLengthRangeType?: number;
            PipeLengthValues?: number[];
            PipeType?: string[];
            PoNumber?: string[];
            PrecipType?: string[];
            PrecipTypeScoreIncludeNulls?: boolean;
            PrecipTypeScoreIsMaxValueExclusive?: boolean;
            PrecipTypeScoreIsMinValueExclusive?: boolean;
            PrecipTypeScoreMaxValue?: number;
            PrecipTypeScoreMinValue?: number;
            PrecipTypeScoreRangeType?: number;
            PrecipTypeScoreValues?: number[];
            PreCleaning?: string[];
            Pressure_ValueIncludeNulls?: boolean;
            Pressure_ValueIsMaxValueExclusive?: boolean;
            Pressure_ValueIsMinValueExclusive?: boolean;
            Pressure_ValueMaxValue?: number;
            Pressure_ValueMinValue?: number;
            Pressure_ValueRangeType?: number;
            Pressure_ValueValues?: number[];
            Project?: string[];
            RehabStatus?: string[];
            RepairsMade?: string[];
            Reverse_Setup_FlagIncludeNulls?: boolean;
            Reverse_Setup_FlagIsMaxValueExclusive?: boolean;
            Reverse_Setup_FlagIsMinValueExclusive?: boolean;
            Reverse_Setup_FlagMaxValue?: number;
            Reverse_Setup_FlagMinValue?: number;
            Reverse_Setup_FlagRangeType?: number;
            Reverse_Setup_FlagValues?: number[];
            ReverseSetup?: boolean;
            ReviewedBySid?: number[];
            ReviewedBySidIsInList?: boolean;
            Reviewer_Certificate_Number?: string[];
            RimToGradeDIncludeNulls?: boolean;
            RimToGradeDIsMaxValueExclusive?: boolean;
            RimToGradeDIsMinValueExclusive?: boolean;
            RimToGradeDMaxValue?: number;
            RimToGradeDMinValue?: number;
            RimToGradeDRangeType?: number;
            RimToGradeDValues?: number[];
            RimToGradeUIncludeNulls?: boolean;
            RimToGradeUIsMaxValueExclusive?: boolean;
            RimToGradeUIsMinValueExclusive?: boolean;
            RimToGradeUMaxValue?: number;
            RimToGradeUMinValue?: number;
            RimToGradeURangeType?: number;
            RimToGradeUValues?: number[];
            RimToInvertDIncludeNulls?: boolean;
            RimToInvertDIsMaxValueExclusive?: boolean;
            RimToInvertDIsMinValueExclusive?: boolean;
            RimToInvertDMaxValue?: number;
            RimToInvertDMinValue?: number;
            RimToInvertDRangeType?: number;
            RimToInvertDValues?: number[];
            RimToInvertUIncludeNulls?: boolean;
            RimToInvertUIsMaxValueExclusive?: boolean;
            RimToInvertUIsMinValueExclusive?: boolean;
            RimToInvertUMaxValue?: number;
            RimToInvertUMinValue?: number;
            RimToInvertURangeType?: number;
            RimToInvertUValues?: number[];
            RootRatingIncludeNulls?: boolean;
            RootRatingIsMaxValueExclusive?: boolean;
            RootRatingIsMinValueExclusive?: boolean;
            RootRatingMaxValue?: number;
            RootRatingMinValue?: number;
            RootRatingRangeType?: number;
            RootRatingValues?: number[];
            SewerCategory?: string[];
            SewerUse?: string[];
            Shape?: string[];
            SmokeId?: number[];
            SmokeIdIsInList?: boolean;
            Spot?: string[];
            SpotScoreIncludeNulls?: boolean;
            SpotScoreIsMaxValueExclusive?: boolean;
            SpotScoreIsMinValueExclusive?: boolean;
            SpotScoreMaxValue?: number;
            SpotScoreMinValue?: number;
            SpotScoreRangeType?: number;
            SpotScoreValues?: number[];
            Street?: string[];
            StructRatingIncludeNulls?: boolean;
            StructRatingIsMaxValueExclusive?: boolean;
            StructRatingIsMinValueExclusive?: boolean;
            StructRatingMaxValue?: number;
            StructRatingMinValue?: number;
            StructRatingRangeType?: number;
            StructRatingValues?: number[];
            SuperAprvlComnts?: string[];
            SurfaceType?: string[];
            TapeLibraryNum?: string[];
            Text1?: string[];
            Text10?: string[];
            Text2?: string[];
            Text3?: string[];
            Text4?: string[];
            Text5?: string[];
            Text6?: string[];
            Text7?: string[];
            Text8?: string[];
            Text9?: string[];
            TotalLengthIncludeNulls?: boolean;
            TotalLengthIsMaxValueExclusive?: boolean;
            TotalLengthIsMinValueExclusive?: boolean;
            TotalLengthMaxValue?: number;
            TotalLengthMinValue?: number;
            TotalLengthRangeType?: number;
            TotalLengthValues?: number[];
            TvDateBegin?: Date;
            TvDateEnd?: Date;
            TvDateIsNull?: boolean;
            TvDateNotInRange?: boolean;
            TvDateRangeIncludeCurrent?: boolean;
            TvDateRangeLast?: number;
            TvDateRangeNext?: number;
            TvDateRangeUnits?: number;
            TvId?: number[];
            TvIdIsInList?: boolean;
            TvReason?: string[];
            Up_Easting?: string[];
            Up_Elevation?: string[];
            Up_Northing?: string[];
            UpdateMap?: boolean;
            UpDepthIncludeNulls?: boolean;
            UpDepthIsMaxValueExclusive?: boolean;
            UpDepthIsMinValueExclusive?: boolean;
            UpDepthMaxValue?: number;
            UpDepthMinValue?: number;
            UpDepthRangeType?: number;
            UpDepthValues?: number[];
            UpLocation?: string[];
            UpMh?: string[];
            UpType?: string[];
            Vertical_Datum?: string[];
            VideoLocation?: string[];
            VideoTapeNum?: string[];
            VtrFormat?: string[];
            Weather?: string[];
            WidthIncludeNulls?: boolean;
            WidthIsMaxValueExclusive?: boolean;
            WidthIsMinValueExclusive?: boolean;
            WidthMaxValue?: number;
            WidthMinValue?: number;
            WidthRangeType?: number;
            WidthValues?: number[];
            WorkOrderId?: string[];
            XIncludeNulls?: boolean;
            XIsMaxValueExclusive?: boolean;
            XIsMinValueExclusive?: boolean;
            XMaxValue?: number;
            XMinValue?: number;
            XRangeType?: number;
            XValues?: number[];
            YearLaidIncludeNulls?: boolean;
            YearLaidIsMaxValueExclusive?: boolean;
            YearLaidIsMinValueExclusive?: boolean;
            YearLaidMaxValue?: number;
            YearLaidMinValue?: number;
            YearLaidRangeType?: number;
            YearLaidValues?: number[];
            YearRenewedIncludeNulls?: boolean;
            YearRenewedIsMaxValueExclusive?: boolean;
            YearRenewedIsMinValueExclusive?: boolean;
            YearRenewedMaxValue?: number;
            YearRenewedMinValue?: number;
            YearRenewedRangeType?: number;
            YearRenewedValues?: number[];
            YIncludeNulls?: boolean;
            YIsMaxValueExclusive?: boolean;
            YIsMinValueExclusive?: boolean;
            YMaxValue?: number;
            YMinValue?: number;
            YRangeType?: number;
            YValues?: number[];
        }
        interface UnitsOfMeasure extends ServiceTypes.CoreRequestBase {
        }
        interface Update extends ServiceTypes.CoreRequestBase {
            CertificateNumber?: string;
            City?: string;
            Coating_Method?: string;
            CondRating?: number;
            Consequence_Of_Failure?: string;
            CounterStart?: string;
            CounterStop?: string;
            Customer?: string;
            CustomFieldValues?: {
                [key: number]: string;
            };
            Date1?: Date;
            Date2?: Date;
            Date3?: Date;
            Date4?: Date;
            Date5?: Date;
            DateCleaned?: Date;
            Deterioration?: string;
            DeterScore?: number;
            Diameter?: number;
            Down_Easting?: string;
            Down_Elevation?: string;
            Down_Northing?: string;
            DownLocation?: string;
            DownMh?: string;
            DownType?: string;
            DrainageArea?: string;
            DwnDepth?: number;
            DyeId?: number;
            FlowControl?: string;
            FlowDepth?: number;
            ForemanRecomnd?: string;
            GPS_Accuracy?: string;
            GroundCond?: string;
            GroundCondScore?: number;
            HydRating?: number;
            InitiatedByApp?: string;
            InspCustFieldCatId?: number;
            InspectedBySid?: number;
            Inspection_Status?: string;
            Inspection_Technology_Used?: string;
            IsImperial?: boolean;
            JointLength?: number;
            JointType?: string;
            LiningMethod?: string;
            Location?: string;
            Location_Code?: string;
            Location_Details?: string;
            MapNumber?: string;
            MasterTapeNum?: string;
            Material?: string;
            MH_Coordinate_System?: string;
            Num1?: number;
            Num2?: number;
            Num3?: number;
            Num4?: number;
            Num5?: number;
            ObservationSum?: string;
            ObservMethod?: number;
            OmRating?: number;
            Owner?: string;
            PipeId?: string;
            PipeLength?: number;
            PipeType?: string;
            PoNumber?: string;
            PrecipType?: string;
            PrecipTypeScore?: number;
            PreCleaning?: string;
            Pressure_Value?: number;
            Project?: string;
            RehabStatus?: string;
            RepairsMade?: string;
            Reverse_Setup_Flag?: number;
            ReverseSetup?: boolean;
            ReviewedBySid?: number;
            Reviewer_Certificate_Number?: string;
            RimToGradeD?: number;
            RimToGradeU?: number;
            RimToInvertD?: number;
            RimToInvertU?: number;
            RootRating?: number;
            SewerCategory?: string;
            SewerUse?: string;
            Shape?: string;
            SmokeId?: number;
            Spot?: string;
            SpotScore?: number;
            Street?: string;
            StructRating?: number;
            SuperAprvlComnts?: string;
            SurfaceType?: string;
            TapeLibraryNum?: string;
            Text1?: string;
            Text10?: string;
            Text2?: string;
            Text3?: string;
            Text4?: string;
            Text5?: string;
            Text6?: string;
            Text7?: string;
            Text8?: string;
            Text9?: string;
            TotalLength?: number;
            TvDate?: Date;
            TvId: number;
            TvReason?: string;
            Up_Easting?: string;
            Up_Elevation?: string;
            Up_Northing?: string;
            UpdateGis?: boolean;
            UpdateMap?: boolean;
            UpDepth?: number;
            UpLocation?: string;
            UpMh?: string;
            UpType?: string;
            Vertical_Datum?: string;
            VideoLocation?: string;
            VideoTapeNum?: string;
            VtrFormat?: string;
            Weather?: string;
            Width?: number;
            WorkOrderId?: string;
            YearLaid?: number;
            YearRenewed?: number;
        }
        interface UpdateObservation extends ServiceTypes.CoreRequestBase {
            Cause?: number;
            CctvCode?: string;
            ClockTo?: number;
            Continuous?: string;
            DistFromDown?: number;
            DistFromUp?: number;
            Grade?: number;
            Joint?: string;
            ObservationId: number;
            ObservDesc?: string;
            ObservDescScore?: number;
            ObservPos?: string;
            ObservRemarks?: string;
            ObservType?: string;
            TapeRead?: string;
            TvImage?: string;
            TvTape?: string;
            ValueDimension1?: number;
            ValueDimension2?: number;
            ValuePercent?: number;
            VCR_Time?: string;
        }
        interface UpstreamNode extends ServiceTypes.CoreRequestBase {
            EntityType: string;
            EntityUid: string;
        }
    }
    namespace Responses {
        interface AddObservation extends ServiceTypes.CoreResponseBase_<TvObservation> {
        }
        interface ById extends ServiceTypes.CoreResponseBase_<TvInspection> {
        }
        interface ByIds extends ServiceTypes.CoreResponseBase_<TvInspection[]> {
        }
        interface ByWorkOrder extends ServiceTypes.CoreResponseBase_<TvInspection[]> {
        }
        interface CctvObservationCodeTypes extends ServiceTypes.CoreResponseBase_<CctvCodeDescGrade[]> {
        }
        interface ChangeCustomFieldCategory extends ServiceTypes.CoreResponseBase_<TvInspectionBase[]> {
        }
        interface CodeDescriptions extends ServiceTypes.CoreResponseBase_<TvInspectionCodeDescs> {
        }
        interface ConfirmDyeLeaks extends ServiceTypes.CoreResponseBase_<{
            [key: number]: boolean;
        }> {
        }
        interface ConfirmSmokeTests extends ServiceTypes.CoreResponseBase_<{
            [key: number]: boolean;
        }> {
        }
        interface Create extends ServiceTypes.CoreResponseBase_<TvInspection> {
        }
        interface CreateFromPacp extends ServiceTypes.CoreResponseBase_<TvInspection> {
        }
        interface CreateSearchDefinition extends ServiceTypes.CoreResponseBase_<SearchDefinition> {
        }
        interface DescriptionScores extends ServiceTypes.CoreResponseBase_<TvInspectionDescScores> {
        }
        interface DownstreamNode extends ServiceTypes.CoreResponseBase_<WorkOrderEntity> {
        }
        interface InspectedBy extends ServiceTypes.CoreResponseBase_<RelEmpToField[]> {
        }
        interface Observation extends ServiceTypes.CoreResponseBase_<TvObservation> {
        }
        interface ObservationCauseCodeDescriptions extends ServiceTypes.CoreResponseBase_<CodeDesc[]> {
        }
        interface ObservationCodeTypes extends ServiceTypes.CoreResponseBase_<CodeDescScore[]> {
        }
        interface Observations extends ServiceTypes.CoreResponseBase_<TvObservation[]> {
        }
        interface ReviewedBy extends ServiceTypes.CoreResponseBase_<RelEmpToField[]> {
        }
        interface Search extends ServiceTypes.CoreResponseBase_<number[]> {
        }
        interface UnitsOfMeasure extends ServiceTypes.CoreResponseBase_<TvInspectionFieldUnits> {
        }
        interface Update extends ServiceTypes.CoreResponseBase_<TvInspectionBase> {
        }
        interface UpdateObservation extends ServiceTypes.CoreResponseBase_<TvObservation> {
        }
        interface UpstreamNode extends ServiceTypes.CoreResponseBase_<WorkOrderEntity> {
        }
    }
    interface ITvInspectionService {
        AddObservation?: (request: Requests.AddObservation) => Promise<Responses.AddObservation>;
        ById?: (request: Requests.ById) => Promise<Responses.ById>;
        ByIds?: (request: Requests.ByIds) => Promise<Responses.ByIds>;
        ByWorkOrder?: (request: Requests.ByWorkOrder) => Promise<Responses.ByWorkOrder>;
        CctvObservationCodeTypes?: (request: Requests.CctvObservationCodeTypes) => Promise<Responses.CctvObservationCodeTypes>;
        ChangeCustomFieldCategory?: (request: Requests.ChangeCustomFieldCategory) => Promise<Responses.ChangeCustomFieldCategory>;
        CodeDescriptions?: (request: Requests.CodeDescriptions) => Promise<Responses.CodeDescriptions>;
        ConfirmDyeLeaks?: (request: Requests.ConfirmDyeLeaks) => Promise<Responses.ConfirmDyeLeaks>;
        ConfirmSmokeTests?: (request: Requests.ConfirmSmokeTests) => Promise<Responses.ConfirmSmokeTests>;
        Create?: (request: Requests.Create) => Promise<Responses.Create>;
        CreateFromPacp?: (request: Requests.CreateFromPacp) => Promise<Responses.CreateFromPacp>;
        CreateSearchDefinition?: (request: Requests.CreateSearchDefinition) => Promise<Responses.CreateSearchDefinition>;
        DescriptionScores?: (request: Requests.DescriptionScores) => Promise<Responses.DescriptionScores>;
        DownstreamNode?: (request: Requests.DownstreamNode) => Promise<Responses.DownstreamNode>;
        InspectedBy?: (request: Requests.InspectedBy) => Promise<Responses.InspectedBy>;
        Observation?: (request: Requests.Observation) => Promise<Responses.Observation>;
        ObservationCauseCodeDescriptions?: (request: Requests.ObservationCauseCodeDescriptions) => Promise<Responses.ObservationCauseCodeDescriptions>;
        ObservationCodeTypes?: (request: Requests.ObservationCodeTypes) => Promise<Responses.ObservationCodeTypes>;
        Observations?: (request: Requests.Observations) => Promise<Responses.Observations>;
        ReviewedBy?: (request: Requests.ReviewedBy) => Promise<Responses.ReviewedBy>;
        Search?: (request: Requests.Search) => Promise<Responses.Search>;
        UnitsOfMeasure?: (request: Requests.UnitsOfMeasure) => Promise<Responses.UnitsOfMeasure>;
        Update?: (request: Requests.Update) => Promise<Responses.Update>;
        UpdateObservation?: (request: Requests.UpdateObservation) => Promise<Responses.UpdateObservation>;
        UpstreamNode?: (request: Requests.UpstreamNode) => Promise<Responses.UpstreamNode>;
    }
}
