import type { IActivityHandler } from "@geocortex/workflow/runtime/IActivityHandler";
import { IApiService } from "cw-sdk/api-service/i-api-service";
import { ServiceTypes } from "cw-sdk/core";
import { checkResponse } from "./utils";

/** An interface that defines the inputs of the activity. */
export interface UseCityworksServiceInputs {
    /**
     * @displayName API Service
     * @description The Cityworks API Service.
     * @required
     */
    service: IApiService;
    /**
     * @description The Cityworks service operation.
     * @required
     */
    path:
    "Ams/Attachments/AddInspectionAttachment" |
    "Ams/Attachments/AddRequestAttachment" |
    "Ams/Attachments/AddWorkOrderAttachment" |
    "Ams/Attachments/DeleteInspectionAttachments" |
    "Ams/Attachments/DeleteRequestAttachments" |
    "Ams/Attachments/DeleteWorkOrderAttachments" |
    "Ams/Attachments/DownloadInspectionAttachment" |
    "Ams/Attachments/DownloadRequestAttachment" |
    "Ams/Attachments/DownloadWorkOrderAttachment" |
    "Ams/Attachments/InspectionAttachmentById" |
    "Ams/Attachments/InspectionAttachments" |
    "Ams/Attachments/RequestAttachmentById" |
    "Ams/Attachments/RequestAttachments" |
    "Ams/Attachments/WorkOrderAttachments" |
    "Ams/Bookmark/AddBookmark" |
    "Ams/Bookmark/AddScale" |
    "Ams/Bookmark/DeleteBookmarks" |
    "Ams/Bookmark/DeleteScales" |
    "Ams/Bookmark/GetBookmarks" |
    "Ams/Bookmark/GetScales" |
    "Ams/Bookmark/SetInitialExtent" |
    "Ams/Bookmark/UpdateBookmark" |
    "Ams/Bookmark/UpdateScale" |
    "Ams/Codes/All" |
    "Ams/Codes/AllCCTVCodeDescScore" |
    "Ams/Codes/AllDescScore" |
    "Ams/Codes/ByCodeType" |
    "Ams/Codes/Export" |
    "Ams/Codes/ExportCCTVCodeDescScore" |
    "Ams/Codes/ExportDescScore" |
    "Ams/Codes/Import" |
    "Ams/Codes/ImportCCTVCodeDescScore" |
    "Ams/Codes/ImportDescScore" |
    "Ams/Comment/Add" |
    "Ams/Comment/ByActivityIds" |
    "Ams/Comment/ByActivitySids" |
    "Ams/Comment/ByActivityTypes" |
    "Ams/Comment/ProblemComments" |
    "Ams/Comment/Update" |
    "Ams/Condition/Current" |
    "Ams/Condition/History" |
    "Ams/Contract/AddLineItem" |
    "Ams/Contract/ByIds" |
    "Ams/Contract/Claims" |
    "Ams/Contract/Create" |
    "Ams/Contract/CreateFundSource" |
    "Ams/Contract/CreateSearchDefinition" |
    "Ams/Contract/CreateSubcontractor" |
    "Ams/Contract/CreateSubmittal" |
    "Ams/Contract/Delete" |
    "Ams/Contract/DeleteFundSource" |
    "Ams/Contract/DeleteLineItems" |
    "Ams/Contract/DeleteSubcontractor" |
    "Ams/Contract/DeleteSubmittal" |
    "Ams/Contract/FundSources" |
    "Ams/Contract/LineItems" |
    "Ams/Contract/LineItemSummary" |
    "Ams/Contract/Permits" |
    "Ams/Contract/Search" |
    "Ams/Contract/Subcontractors" |
    "Ams/Contract/Submittals" |
    "Ams/Contract/UninvoicedLineItemCosts" |
    "Ams/Contract/Update" |
    "Ams/Contract/UpdateLineItem" |
    "Ams/Contract/UpdateSubcontractor" |
    "Ams/Contract/UpdateSubmittal" |
    "Ams/Contract/User" |
    "Ams/Contractor/Add" |
    "Ams/Contractor/AddKeywords" |
    "Ams/Contractor/All" |
    "Ams/Contractor/ById" |
    "Ams/Contractor/Delete" |
    "Ams/Contractor/DeleteKeywords" |
    "Ams/Contractor/Keywords" |
    "Ams/Contractor/Search" |
    "Ams/Contractor/Update" |
    "Ams/Crew/ByEmployee" |
    "Ams/Crew/ByIds" |
    "Ams/Crew/Employees" |
    "Ams/Crew/Equipment" |
    "Ams/Crew/Material" |
    "Ams/CustomerAccount/Add" |
    "Ams/CustomerAccount/ByAccountNumbers" |
    "Ams/CustomerAccount/ByIds" |
    "Ams/CustomerAccount/Delete" |
    "Ams/CustomerAccount/Import" |
    "Ams/CustomerAccount/Search" |
    "Ams/CustomerAccount/Update" |
    "Ams/CustomerCall/AddToRequest" |
    "Ams/CustomerCall/ByIncidentNum" |
    "Ams/CustomerCall/ByRequestId" |
    "Ams/CustomerCall/ByRequestIds" |
    "Ams/CustomerCall/CallerQuestions" |
    "Ams/CustomerCall/CallerQuestionsByRequestIds" |
    "Ams/CustomerCall/Delete" |
    "Ams/CustomerCall/Move" |
    "Ams/CustomerCall/MoveToRequest" |
    "Ams/CustomerCall/Update" |
    "Ams/Designer/AddAttachmentMapping" |
    "Ams/Designer/AddCodeDescription" |
    "Ams/Designer/AddCodeDescScore" |
    "Ams/Designer/AddCodeType" |
    "Ams/Designer/AddDescScore" |
    "Ams/Designer/AddDomain" |
    "Ams/Designer/AddEmployeeSkillCode" |
    "Ams/Designer/AddGroup" |
    "Ams/Designer/AddRole" |
    "Ams/Designer/AddUsersToRole" |
    "Ams/Designer/AttachmentMappings" |
    "Ams/Designer/CctvCodes" |
    "Ams/Designer/CodeDescriptions" |
    "Ams/Designer/CodeDescScores" |
    "Ams/Designer/CodeTypes" |
    "Ams/Designer/CreateUser" |
    "Ams/Designer/DeleteAttachmentMappings" |
    "Ams/Designer/DeleteCodeDescriptions" |
    "Ams/Designer/DeleteDomains" |
    "Ams/Designer/DeleteEmployeeSkillCodes" |
    "Ams/Designer/DeleteGroups" |
    "Ams/Designer/DeleteLogin" |
    "Ams/Designer/DeleteRoles" |
    "Ams/Designer/DescScores" |
    "Ams/Designer/Domains" |
    "Ams/Designer/EmployeeGroups" |
    "Ams/Designer/GroupMembers" |
    "Ams/Designer/Groups" |
    "Ams/Designer/RemoveUsersFromRole" |
    "Ams/Designer/Roles" |
    "Ams/Designer/SaveCctvCode" |
    "Ams/Designer/UnlockUsers" |
    "Ams/Designer/UpdateAttachmentMapping" |
    "Ams/Designer/UpdateCodeDescription" |
    "Ams/Designer/UpdateCodeDescScore" |
    "Ams/Designer/UpdateCodeType" |
    "Ams/Designer/UpdateDescScore" |
    "Ams/Designer/UpdateDomain" |
    "Ams/Designer/UpdateGroup" |
    "Ams/Designer/UserRoles" |
    "Ams/Designer/UsersInRole" |
    "Ams/Designer/UserStatus" |
    "Ams/Employee/Add" |
    "Ams/Employee/AddLicensedItems" |
    "Ams/Employee/All" |
    "Ams/Employee/ByGroupId" |
    "Ams/Employee/ById" |
    "Ams/Employee/ByIds" |
    "Ams/Employee/Delete" |
    "Ams/Employee/DeleteLicensedItems" |
    "Ams/Employee/Groups" |
    "Ams/Employee/NamesAreUnique" |
    "Ams/Employee/Search" |
    "Ams/Employee/Update" |
    "Ams/Entity/AddAlias" |
    "Ams/Entity/AddSplit" |
    "Ams/Entity/AliasAssets" |
    "Ams/Entity/Aliases" |
    "Ams/Entity/AllAliases" |
    "Ams/Entity/Attributes" |
    "Ams/Entity/CloneWorkOrderEntities" |
    "Ams/Entity/Configuration" |
    "Ams/Entity/CostHistory" |
    "Ams/Entity/CostTotal" |
    "Ams/Entity/DistinctValues" |
    "Ams/Entity/DomainTypes" |
    "Ams/Entity/EntityUidField" |
    "Ams/Entity/FiveNumberSummary" |
    "Ams/Entity/GetByIdentifier" |
    "Ams/Entity/GetByIdentifiers" |
    "Ams/Entity/Groups" |
    "Ams/Entity/ProcessSplits" |
    "Ams/Entity/RemoveAlias" |
    "Ams/Entity/Search" |
    "Ams/Entity/SearchAsWorkOrderEntity" |
    "Ams/Entity/SplitEntities" |
    "Ams/Entity/Splits" |
    "Ams/Entity/SubTypes" |
    "Ams/Entity/TypeRelationships" |
    "Ams/Entity/Types" |
    "Ams/Entity/VisibleFields" |
    "Ams/Entity/WorkActivityHistory" |
    "Ams/Equipment/Add" |
    "Ams/Equipment/All" |
    "Ams/Equipment/ById" |
    "Ams/Equipment/ByIds" |
    "Ams/Equipment/Delete" |
    "Ams/Equipment/Search" |
    "Ams/Equipment/Update" |
    "Ams/EquipmentChangeOut/AddChangeOutRead" |
    "Ams/EquipmentChangeOut/AddOperation" |
    "Ams/EquipmentChangeOut/Attach" |
    "Ams/EquipmentChangeOut/ById" |
    "Ams/EquipmentChangeOut/ByIds" |
    "Ams/EquipmentChangeOut/Delete" |
    "Ams/EquipmentChangeOut/DeleteChangeOutReads" |
    "Ams/EquipmentChangeOut/DeleteOperations" |
    "Ams/EquipmentChangeOut/Detach" |
    "Ams/EquipmentChangeOut/DirectParent" |
    "Ams/EquipmentChangeOut/Entities" |
    "Ams/EquipmentChangeOut/Entity" |
    "Ams/EquipmentChangeOut/History" |
    "Ams/EquipmentChangeOut/Read" |
    "Ams/EquipmentChangeOut/ReadConfigs" |
    "Ams/EquipmentChangeOut/Related" |
    "Ams/EquipmentChangeOut/Replace" |
    "Ams/EquipmentChangeOut/UpdateChangeOutRead" |
    "Ams/EquipmentChangeOut/UpdateOperation" |
    "Ams/EquipmentCost/AddWorkOrderCosts" |
    "Ams/EquipmentCost/DeleteWorkOrderCosts" |
    "Ams/EquipmentCost/WorkOrderCostsByWorkOrder" |
    "Ams/EquipmentReservation/CheckedOut" |
    "Ams/EquipmentReservation/CheckIn" |
    "Ams/EquipmentReservation/CheckOut" |
    "Ams/EquipmentReservation/CheckOutHistory" |
    "Ams/EquipmentReservation/DeleteReservation" |
    "Ams/EquipmentReservation/Reservations" |
    "Ams/EquipmentReservation/Reserve" |
    "Ams/EquipmentReservation/Status" |
    "Ams/EquipmentReservation/UpdateReservation" |
    "Ams/EventLayer/All" |
    "Ams/EventLayer/ById" |
    "Ams/GISService/AddGISServiceDefinition" |
    "Ams/GISService/AddGISServiceEndPointSecurity" |
    "Ams/GISService/CloneGISServiceDefinition" |
    "Ams/GISService/DeleteGISServiceDefinitions" |
    "Ams/GISService/DeleteGISServiceEndPointSecurities" |
    "Ams/GISService/GISServiceDefinitions" |
    "Ams/GISService/UpdateGISServiceEndPointSecurity" |
    "Ams/GISService/ValidateServiceSecurity" |
    "Ams/Inbox/CopyWidgetContainerTab" |
    "Ams/Inbox/CreateWidget" |
    "Ams/Inbox/CreateWidgetContainer" |
    "Ams/Inbox/CreateWidgetContainerTab" |
    "Ams/Inbox/CreateWidgetZone" |
    "Ams/Inbox/DeleteWidget" |
    "Ams/Inbox/DeleteWidgetContainer" |
    "Ams/Inbox/DeleteWidgetContainerTab" |
    "Ams/Inbox/DeleteWidgetZone" |
    "Ams/Inbox/MoveWidget" |
    "Ams/Inbox/MoveWidgetContainerTab" |
    "Ams/Inbox/MoveWidgetZone" |
    "Ams/Inbox/UpdateChartWidget" |
    "Ams/Inbox/UpdateHtmlWidget" |
    "Ams/Inbox/UpdateNotesWidget" |
    "Ams/Inbox/UpdateReportLinksWidget" |
    "Ams/Inbox/UpdateSearchResultsWidget" |
    "Ams/Inbox/UpdateWeatherWidget" |
    "Ams/Inbox/UpdateWidgetContainer" |
    "Ams/Inbox/UpdateWidgetContainerTab" |
    "Ams/Inbox/UpdateWidgetZone" |
    "Ams/Inspection/AddEntity" |
    "Ams/Inspection/Answers" |
    "Ams/Inspection/AuditLog" |
    "Ams/Inspection/ById" |
    "Ams/Inspection/ByIds" |
    "Ams/Inspection/ByWorkOrderIds" |
    "Ams/Inspection/Cancel" |
    "Ams/Inspection/Close" |
    "Ams/Inspection/Create" |
    "Ams/Inspection/CreateFromParent" |
    "Ams/Inspection/CreateFromServiceRequest" |
    "Ams/Inspection/CreateFromWorkOrder" |
    "Ams/Inspection/CreateSearchDefinition" |
    "Ams/Inspection/CycleFrom" |
    "Ams/Inspection/CycleIntervals" |
    "Ams/Inspection/CycleTypes" |
    "Ams/Inspection/Delete" |
    "Ams/Inspection/Districts" |
    "Ams/Inspection/InspectionInspections" |
    "Ams/Inspection/InspectionServiceRequests" |
    "Ams/Inspection/InspectionWorkOrders" |
    "Ams/Inspection/Move" |
    "Ams/Inspection/Priorities" |
    "Ams/Inspection/QA" |
    "Ams/Inspection/Questions" |
    "Ams/Inspection/RemoveEntity" |
    "Ams/Inspection/Resolutions" |
    "Ams/Inspection/Search" |
    "Ams/Inspection/SearchObject" |
    "Ams/Inspection/Shops" |
    "Ams/Inspection/Statuses" |
    "Ams/Inspection/SubmitTos" |
    "Ams/Inspection/Templates" |
    "Ams/Inspection/Update" |
    "Ams/InspectionTemplate/ByIds" |
    "Ams/InspectionTemplate/CreateSearchDefinition" |
    "Ams/InspectionTemplate/EntityTypes" |
    "Ams/InspectionTemplate/QA" |
    "Ams/InspectionTemplate/Search" |
    "Ams/InspectionTemplate/Templates" |
    "Ams/InspectionTemplate/TestTypes" |
    "Ams/LaborCost/AddRequestCosts" |
    "Ams/LaborCost/AddWorkOrderCosts" |
    "Ams/LaborCost/CostCodes" |
    "Ams/LaborCost/DeleteRequestCosts" |
    "Ams/LaborCost/DeleteWorkOrderCosts" |
    "Ams/LaborCost/JobCodes" |
    "Ams/LaborCost/RequestCostsByRequest" |
    "Ams/LaborCost/WorkOrderCostsByWorkOrder" |
    "Ams/Material/All" |
    "Ams/Material/ById" |
    "Ams/Material/ByIds" |
    "Ams/Material/ByParent" |
    "Ams/Material/ByStoreroom" |
    "Ams/Material/ByStoreroomAndId" |
    "Ams/Material/Keywords" |
    "Ams/Material/MaterialBom" |
    "Ams/Material/MaterialCategories" |
    "Ams/Material/MaterialNodes" |
    "Ams/Material/Search" |
    "Ams/MaterialCost/AddWorkOrderCosts" |
    "Ams/MaterialCost/DeleteWorkOrderCosts" |
    "Ams/MaterialCost/WorkOrderCostsByWorkOrder" |
    "Ams/PavementInspection/AddDistress" |
    "Ams/PavementInspection/AddSample" |
    "Ams/PavementInspection/ById" |
    "Ams/PavementInspection/ByIds" |
    "Ams/PavementInspection/CodeDesc" |
    "Ams/PavementInspection/Create" |
    "Ams/PavementInspection/CreateSearchDefinition" |
    "Ams/PavementInspection/DistressCodes" |
    "Ams/PavementInspection/Distresses" |
    "Ams/PavementInspection/Samples" |
    "Ams/PavementInspection/Search" |
    "Ams/PavementInspection/Update" |
    "Ams/PavementInspection/UpdateDistress" |
    "Ams/PavementInspection/UpdateSample" |
    "Ams/PluginLayout/Definition" |
    "Ams/PluginLayout/Definitions" |
    "Ams/PluginLayout/Public" |
    "Ams/PluginLayout/PublicDefinitions" |
    "Ams/Preferences/Global" |
    "Ams/Preferences/User" |
    "Ams/Preferences/UserSave" |
    "Ams/Projects/ByContractIds" |
    "Ams/Projects/ByIds" |
    "Ams/Projects/Create" |
    "Ams/Projects/CreateSearchDefinition" |
    "Ams/Projects/QuickView" |
    "Ams/Projects/Search" |
    "Ams/Projects/Update" |
    "Ams/Reading/Add" |
    "Ams/Reading/ByEntity" |
    "Ams/Reading/Configuration" |
    "Ams/Reading/Update" |
    "Ams/RecentActivity/CaseViewed" |
    "Ams/RecentActivity/InspectionViewed" |
    "Ams/RecentActivity/RequestViewed" |
    "Ams/RecentActivity/User" |
    "Ams/RecentActivity/WorkOrderViewed" |
    "Ams/Relates/ByTableName" |
    "Ams/Relates/EquipChangeOutChangedBy" |
    "Ams/Relates/InspectionCancelledBy" |
    "Ams/Relates/InspectionClosedBy" |
    "Ams/Relates/InspectionEditAfterClose" |
    "Ams/Relates/InspectionInitiatedBy" |
    "Ams/Relates/InspectionInspectedBy" |
    "Ams/Relates/InspectionSubmitTo" |
    "Ams/Relates/ProblemLeafDispatchTo" |
    "Ams/Relates/ProblemLeafSubmitTo" |
    "Ams/Relates/ProjectApprovedBy" |
    "Ams/Relates/ProjectAssignedTo" |
    "Ams/Relates/ProjectInitiatedBy" |
    "Ams/Relates/RequestCancelledBy" |
    "Ams/Relates/RequestClosedBy" |
    "Ams/Relates/RequestDispatchTo" |
    "Ams/Relates/RequestEditAfterClose" |
    "Ams/Relates/RequestInitiatedBy" |
    "Ams/Relates/RequestSubmitTo" |
    "Ams/Relates/SearchViewCost" |
    "Ams/Relates/TableFields" |
    "Ams/Relates/TaskAssignTo" |
    "Ams/Relates/TransferRequestedBy" |
    "Ams/Relates/WorkOrderCancelledBy" |
    "Ams/Relates/WorkOrderClosedBy" |
    "Ams/Relates/WorkOrderCompletedBy" |
    "Ams/Relates/WorkOrderEditAfterClose" |
    "Ams/Relates/WorkOrderInitiatedBy" |
    "Ams/Relates/WorkOrderRequestedBy" |
    "Ams/Relates/WorkOrderSubmitTo" |
    "Ams/Relates/WorkOrderSupervisors" |
    "Ams/Search/AssetCalculationResultSaved" |
    "Ams/Search/Definition" |
    "Ams/Search/DefinitionNames" |
    "Ams/Search/Definitions" |
    "Ams/Search/DeleteDefinitions" |
    "Ams/Search/DisplayFields" |
    "Ams/Search/Execute" |
    "Ams/Search/GISSaved" |
    "Ams/Search/InspectionSaved" |
    "Ams/Search/MaterialSaved" |
    "Ams/Search/PllSaved" |
    "Ams/Search/RecentActivity" |
    "Ams/Search/RequestSaved" |
    "Ams/Search/RequisitionSaved" |
    "Ams/Search/SavedByType" |
    "Ams/Search/SaveDefinition" |
    "Ams/Search/StoreTransactionSaved" |
    "Ams/Search/Types" |
    "Ams/Search/UpdateEurl" |
    "Ams/Search/WorkActivitySaved" |
    "Ams/Search/WorkOrderEntitySaved" |
    "Ams/Search/WorkOrderSaved" |
    "Ams/Security/Contract" |
    "Ams/Security/Contracts" |
    "Ams/Security/Employee" |
    "Ams/Security/Inspection" |
    "Ams/Security/Inspections" |
    "Ams/Security/InspectionTemplate" |
    "Ams/Security/InspectionTemplates" |
    "Ams/Security/Problem" |
    "Ams/Security/Problems" |
    "Ams/Security/Projects" |
    "Ams/Security/Search" |
    "Ams/Security/ServiceRequest" |
    "Ams/Security/ServiceRequests" |
    "Ams/Security/WorkOrder" |
    "Ams/Security/WorkOrderBySid" |
    "Ams/Security/WorkOrders" |
    "Ams/Security/WorkOrderTemplate" |
    "Ams/ServiceRequest/AddComments" |
    "Ams/ServiceRequest/AllStreetCode" |
    "Ams/ServiceRequest/AuditLog" |
    "Ams/ServiceRequest/ById" |
    "Ams/ServiceRequest/ByIds" |
    "Ams/ServiceRequest/ByIncidentAndEmail" |
    "Ams/ServiceRequest/ByOtherSystemId" |
    "Ams/ServiceRequest/Cancel" |
    "Ams/ServiceRequest/ChangeCustomFieldCategory" |
    "Ams/ServiceRequest/ChangeProblem" |
    "Ams/ServiceRequest/Close" |
    "Ams/ServiceRequest/Combine" |
    "Ams/ServiceRequest/Comments" |
    "Ams/ServiceRequest/CommentsByRequestIds" |
    "Ams/ServiceRequest/Create" |
    "Ams/ServiceRequest/CreateSearchDefinition" |
    "Ams/ServiceRequest/CustomFieldCategories" |
    "Ams/ServiceRequest/CustomFields" |
    "Ams/ServiceRequest/DefaultStatus" |
    "Ams/ServiceRequest/Delete" |
    "Ams/ServiceRequest/DispatchTo" |
    "Ams/ServiceRequest/LinkCases" |
    "Ams/ServiceRequest/LinkInspections" |
    "Ams/ServiceRequest/LinkWorkOrders" |
    "Ams/ServiceRequest/Move" |
    "Ams/ServiceRequest/Priorities" |
    "Ams/ServiceRequest/ProblemLeafByOtherSysCodeDescs" |
    "Ams/ServiceRequest/ProblemLeafBySid" |
    "Ams/ServiceRequest/ProblemNodes" |
    "Ams/ServiceRequest/Problems" |
    "Ams/ServiceRequest/ProblemsByKeywords" |
    "Ams/ServiceRequest/QA" |
    "Ams/ServiceRequest/Reopen" |
    "Ams/ServiceRequest/RequestInspections" |
    "Ams/ServiceRequest/RequestWorkOrders" |
    "Ams/ServiceRequest/Search" |
    "Ams/ServiceRequest/SearchObject" |
    "Ams/ServiceRequest/Statuses" |
    "Ams/ServiceRequest/SubmitTo" |
    "Ams/ServiceRequest/TemplateCustomFields" |
    "Ams/ServiceRequest/Uncancel" |
    "Ams/ServiceRequest/UnlinkInspections" |
    "Ams/ServiceRequest/UnlinkWorkOrders" |
    "Ams/ServiceRequest/Update" |
    "Ams/ServiceRequestTemplate/ByIds" |
    "Ams/ServiceRequestTemplate/CreateSearchDefinition" |
    "Ams/ServiceRequestTemplate/QA" |
    "Ams/ServiceRequestTemplate/Search" |
    "Ams/ServiceRequestTemplate/Templates" |
    "Ams/ServiceRequestTemplate/WorkOrderTemplates" |
    "Ams/Storeroom/Accounts" |
    "Ams/Storeroom/AddAudit" |
    "Ams/Storeroom/AddIssue" |
    "Ams/Storeroom/AddReceive" |
    "Ams/Storeroom/AddRequisition" |
    "Ams/Storeroom/AddRequisitionItem" |
    "Ams/Storeroom/AddSupplier" |
    "Ams/Storeroom/AddSupplierMaterial" |
    "Ams/Storeroom/AddTransfer" |
    "Ams/Storeroom/AssemblyMaterial" |
    "Ams/Storeroom/BuildAssemblyMaterial" |
    "Ams/Storeroom/MaterialsByEmployeeSid" |
    "Ams/Storeroom/MaterialSearch" |
    "Ams/Storeroom/RequisitionItems" |
    "Ams/Storeroom/Requisitions" |
    "Ams/Storeroom/SearchSuppliersByUid" |
    "Ams/Storeroom/StoreDomainsByEmployee" |
    "Ams/Storeroom/Storerooms" |
    "Ams/Storeroom/StoreroomSecurity" |
    "Ams/Storeroom/StoreroomStocks" |
    "Ams/Storeroom/SupplierMaterial" |
    "Ams/Storeroom/Suppliers" |
    "Ams/Storeroom/UpdateRequisition" |
    "Ams/Storeroom/UpdateStoreroomStock" |
    "Ams/Storeroom/UpdateSupplier" |
    "Ams/Storeroom/UpdateSupplierMaterial" |
    "Ams/Tasks/Add" |
    "Ams/Tasks/ById" |
    "Ams/Tasks/ByWorkOrder" |
    "Ams/Tasks/ByWorkOrderTemplate" |
    "Ams/Tasks/Delete" |
    "Ams/Tasks/Keywords" |
    "Ams/Tasks/Statuses" |
    "Ams/Tasks/TaskCodes" |
    "Ams/Tasks/TaskNodes" |
    "Ams/Tasks/Template" |
    "Ams/Tasks/Templates" |
    "Ams/Tasks/Update" |
    "Ams/TvInspection/AddObservation" |
    "Ams/TvInspection/ById" |
    "Ams/TvInspection/ByIds" |
    "Ams/TvInspection/ByWorkOrder" |
    "Ams/TvInspection/CctvObservationCodeTypes" |
    "Ams/TvInspection/ChangeCustomFieldCategory" |
    "Ams/TvInspection/CodeDescriptions" |
    "Ams/TvInspection/ConfirmDyeLeaks" |
    "Ams/TvInspection/ConfirmSmokeTests" |
    "Ams/TvInspection/Create" |
    "Ams/TvInspection/CreateFromPacp" |
    "Ams/TvInspection/CreateSearchDefinition" |
    "Ams/TvInspection/DescriptionScores" |
    "Ams/TvInspection/DownstreamNode" |
    "Ams/TvInspection/InspectedBy" |
    "Ams/TvInspection/Observation" |
    "Ams/TvInspection/ObservationCauseCodeDescriptions" |
    "Ams/TvInspection/ObservationCodeTypes" |
    "Ams/TvInspection/Observations" |
    "Ams/TvInspection/ReviewedBy" |
    "Ams/TvInspection/Search" |
    "Ams/TvInspection/UnitsOfMeasure" |
    "Ams/TvInspection/Update" |
    "Ams/TvInspection/UpdateObservation" |
    "Ams/TvInspection/UpstreamNode" |
    "Ams/UniversalCustomField/Add" |
    "Ams/UniversalCustomField/ById" |
    "Ams/UniversalCustomField/ByType" |
    "Ams/UniversalCustomField/Contract" |
    "Ams/UniversalCustomField/CustomerCall" |
    "Ams/UniversalCustomField/Delete" |
    "Ams/UniversalCustomField/Inspection" |
    "Ams/UniversalCustomField/MoveField" |
    "Ams/UniversalCustomField/ServiceRequest" |
    "Ams/UniversalCustomField/Update" |
    "Ams/UniversalCustomField/WorkOrder" |
    "Ams/WorkOrder/AddComments" |
    "Ams/WorkOrder/AddEntities" |
    "Ams/WorkOrder/AuditLog" |
    "Ams/WorkOrder/ById" |
    "Ams/WorkOrder/ByIds" |
    "Ams/WorkOrder/BySid" |
    "Ams/WorkOrder/BySids" |
    "Ams/WorkOrder/Cancel" |
    "Ams/WorkOrder/Categories" |
    "Ams/WorkOrder/ChangeCustomFieldCategory" |
    "Ams/WorkOrder/Close" |
    "Ams/WorkOrder/Combine" |
    "Ams/WorkOrder/Comments" |
    "Ams/WorkOrder/CommentsByWorkOrderIds" |
    "Ams/WorkOrder/Create" |
    "Ams/WorkOrder/CreateFromInspection" |
    "Ams/WorkOrder/CreateFromParent" |
    "Ams/WorkOrder/CreateFromServiceRequest" |
    "Ams/WorkOrder/CreateSearchDefinition" |
    "Ams/WorkOrder/CustomFields" |
    "Ams/WorkOrder/CustomFieldsByWorkOrderSids" |
    "Ams/WorkOrder/CycleFrom" |
    "Ams/WorkOrder/CycleIntervals" |
    "Ams/WorkOrder/CycleTypes" |
    "Ams/WorkOrder/Delete" |
    "Ams/WorkOrder/Entities" |
    "Ams/WorkOrder/ExpenseTypes" |
    "Ams/WorkOrder/InstructionsByWorkOrderIds" |
    "Ams/WorkOrder/InstructionsByWorkOrderSids" |
    "Ams/WorkOrder/LinkInspections" |
    "Ams/WorkOrder/LinkServiceRequests" |
    "Ams/WorkOrder/Move" |
    "Ams/WorkOrder/Priorities" |
    "Ams/WorkOrder/RemoveEntities" |
    "Ams/WorkOrder/ReOpen" |
    "Ams/WorkOrder/Search" |
    "Ams/WorkOrder/SearchForSids" |
    "Ams/WorkOrder/SearchObject" |
    "Ams/WorkOrder/Stages" |
    "Ams/WorkOrder/Statuses" |
    "Ams/WorkOrder/SubmitTos" |
    "Ams/WorkOrder/Supervisors" |
    "Ams/WorkOrder/Template" |
    "Ams/WorkOrder/TemplateCustomFields" |
    "Ams/WorkOrder/Templates" |
    "Ams/WorkOrder/Uncancel" |
    "Ams/WorkOrder/UnlinkInspections" |
    "Ams/WorkOrder/UnlinkServiceRequests" |
    "Ams/WorkOrder/Update" |
    "Ams/WorkOrder/UpdateEntity" |
    "Ams/WorkOrder/WorkOrderInspections" |
    "Ams/WorkOrder/WorkOrderServiceRequests" |
    "Ams/WorkOrder/WorkOrderWorkOrders" |
    "Ams/WorkOrderEntity/ByIds" |
    "Ams/WorkOrderEntity/CreateSearchDefinition" |
    "Ams/WorkOrderEntity/Search" |
    "Ams/WorkOrderTemplate/ByIds" |
    "Ams/WorkOrderTemplate/ByProblemSids" |
    "Ams/WorkOrderTemplate/CustomFieldCategories" |
    "Ams/WorkOrderTemplate/CustomFields" |
    "Ams/WorkOrderTemplate/Search" |
    "Ams/WorkOrderTemplate/TemplateInspections" |
    "Ams/WorkOrderTemplate/TemplateNames" |
    "General/ActivityLink/Add" |
    "General/ActivityLink/ByActivityIds" |
    "General/ActivityLink/ByActivitySids" |
    "General/ActivityLink/CloneByActivitySid" |
    "General/ActivityLink/Delete" |
    "General/ActivityLink/Remove" |
    "General/AppData/CurrentLocation" |
    "General/AppData/SelectedEntities" |
    "General/Authentication/Authenticate" |
    "General/Authentication/CityworksOnlineAuthenticate" |
    "General/Authentication/CityworksOnlineSites" |
    "General/Authentication/Domains" |
    "General/Authentication/User" |
    "General/Authentication/Validate" |
    "General/Authentication/Version" |
    "General/CostSummary/WorkOrderEntity" |
    "General/CostSummary/WorkOrderEntitySearch" |
    "General/CwMetaData/ByTableNameSids" |
    "General/Localization/LocalizationSettings" |
    "General/Localization/TimeZones" |
    "General/MessageQueue/ByIds" |
    "General/MessageQueue/Delete" |
    "General/MessageQueue/Preferences" |
    "General/MessageQueue/Search" |
    "General/MessageQueue/Update" |
    "General/MessageQueue/UpdateMessageStatus" |
    "General/MessageQueue/WebHooks" |
    "General/PavementManagementInterface/ExportInspections" |
    "General/PavementManagementInterface/ExportInventory" |
    "General/PavementManagementInterface/ExportWorkHistory" |
    "General/PavementManagementInterface/GeneratePaverData" |
    "General/PavementManagementInterface/GetPavementInspectionsByIds" |
    "General/PavementManagementInterface/GISSavedSearches" |
    "General/PavementManagementInterface/ImportInspection" |
    "General/PavementManagementInterface/ImportInspections" |
    "General/PavementManagementInterface/PavementInspectionSearch" |
    "General/PavementManagementInterface/ProcessInspectionXmlFile" |
    "General/PavementManagementInterface/ProcessInventoryXmlFile" |
    "General/PavementManagementInterface/ProcessProjectXmlFile" |
    "General/PavementManagementInterface/ProcessRecommendedWorkCsvFile" |
    "General/PavementManagementInterface/ProcessRecommendedWorkXmlFile" |
    "General/PavementManagementInterface/TemplateMapping" |
    "General/QuickSearch/QuickSearch" |
    "General/Token/RevokeUser" |
    "General/WebHookEvent/ProcessMessages" |
    "Gis/MapService/Configuration" |
    "Gis/MapService/Domain" |
    "Gis/MapService/DownloadMobileMapCache" |
    "Gis/MapService/InitialExtent" |
    "Gis/MapService/InspectionConfiguration" |
    "Gis/MapService/ServiceRequestConfiguration" |
    "Gis/MapService/User" |
    "Gis/MapService/WorkOrderConfiguration" |
    "PLL/BusinessCase/Add" |
    "PLL/BusinessCase/Update" |
    "PLL/Case/Create" |
    "PLL/Case/CreateChild" |
    "PLL/CaseAddress/Add" |
    "PLL/CaseAddress/ByCaObjectId" |
    "PLL/CaseAddress/Delete" |
    "PLL/CaseAddress/DeleteByCaObjectId" |
    "PLL/CaseAddress/Search" |
    "PLL/CaseAddress/SearchObject" |
    "PLL/CaseAsset/ByCaObjectId" |
    "PLL/CaseAsset/DeleteByCaObjectId" |
    "PLL/CaseAsset/Search" |
    "PLL/CaseAsset/SearchObject" |
    "PLL/CaseChildObject/ByCaObjectId" |
    "PLL/CaseChildObject/DeleteByCaObjectId" |
    "PLL/CaseChildObject/GetList" |
    "PLL/CaseChildObject/Search" |
    "PLL/CaseChildObject/SearchObject" |
    "PLL/CaseCondition/Add" |
    "PLL/CaseCondition/ByCaObjectId" |
    "PLL/CaseCondition/DeleteByCaObjectId" |
    "PLL/CaseCondition/Search" |
    "PLL/CaseCondition/SearchObject" |
    "PLL/CaseContractor/Add" |
    "PLL/CaseContractor/ByCaObjectId" |
    "PLL/CaseContractor/DeleteByCaObjectId" |
    "PLL/CaseContractor/Search" |
    "PLL/CaseContractor/SearchObject" |
    "PLL/CaseCorrections/Add" |
    "PLL/CaseCorrections/ByCaTaskIds" |
    "PLL/CaseCorrections/Search" |
    "PLL/CaseCorrections/Update" |
    "PLL/CaseCorrStatus/Add" |
    "PLL/CaseCorrStatus/ByCaCorrectionsIds" |
    "PLL/CaseCorrStatus/Search" |
    "PLL/CaseDataDetail/Add" |
    "PLL/CaseDataDetail/Search" |
    "PLL/CaseDataDetail/SearchObject" |
    "PLL/CaseDataDetail/Update" |
    "PLL/CaseDataDetail/UpdateLock" |
    "PLL/CaseDataDetail/WIPAdd" |
    "PLL/CaseDataGroup/Add" |
    "PLL/CaseDataGroup/AddDefault" |
    "PLL/CaseDataGroup/ByCaObjectId" |
    "PLL/CaseDataGroup/CheckGISChanges" |
    "PLL/CaseDataGroup/DeleteByCaObjectId" |
    "PLL/CaseDataGroup/Search" |
    "PLL/CaseDataGroup/UpdateFromAsset" |
    "PLL/CaseDataListValues/Add" |
    "PLL/CaseDataListValues/Delete" |
    "PLL/CaseDataListValues/Search" |
    "PLL/CaseDataListValues/SearchObject" |
    "PLL/CaseDeposit/Add" |
    "PLL/CaseDeposit/AddDefault" |
    "PLL/CaseDeposit/ByCaObjectId" |
    "PLL/CaseDeposit/Delete" |
    "PLL/CaseDeposit/DeleteByCaObjectId" |
    "PLL/CaseDeposit/Search" |
    "PLL/CaseFees/Add" |
    "PLL/CaseFees/AddDefault" |
    "PLL/CaseFees/ByCaObjectId" |
    "PLL/CaseFees/Delete" |
    "PLL/CaseFees/DeleteByCaObjectId" |
    "PLL/CaseFees/Search" |
    "PLL/CaseFeesDataDetail/Add" |
    "PLL/CaseFeesDataDetail/Delete" |
    "PLL/CaseFeesDataDetail/Search" |
    "PLL/CaseFeesDataGroup/Add" |
    "PLL/CaseFeesDataGroup/Delete" |
    "PLL/CaseFeesDataGroup/Search" |
    "PLL/CaseFlags/Add" |
    "PLL/CaseFlags/ByCaObjectId" |
    "PLL/CaseFlags/Delete" |
    "PLL/CaseFlags/DeleteByCaObjectId" |
    "PLL/CaseFlags/Search" |
    "PLL/CaseInspectionRequest/Add" |
    "PLL/CaseInspectionRequest/ByCaObjectId" |
    "PLL/CaseInspectionRequest/Delete" |
    "PLL/CaseInspectionRequest/DeleteByCaObjectId" |
    "PLL/CaseInspectionRequest/Search" |
    "PLL/CaseInstReleases/Add" |
    "PLL/CaseInstReleases/Delete" |
    "PLL/CaseInstReleases/Search" |
    "PLL/CaseInstrument/Add" |
    "PLL/CaseInstrument/ByCaObjectId" |
    "PLL/CaseInstrument/Delete" |
    "PLL/CaseInstrument/DeleteByCaObjectId" |
    "PLL/CaseInstrument/GetList" |
    "PLL/CaseInstrument/Search" |
    "PLL/CaseLicense/Add" |
    "PLL/CaseLicense/ByCaObjectId" |
    "PLL/CaseLicense/Delete" |
    "PLL/CaseLicense/DeleteByCaObjectId" |
    "PLL/CaseLicense/Search" |
    "PLL/CaseNotes/Add" |
    "PLL/CaseNotes/ByCaObjectId" |
    "PLL/CaseNotes/Delete" |
    "PLL/CaseNotes/DeleteByCaObjectId" |
    "PLL/CaseNotes/Search" |
    "PLL/CaseObject/ByIds" |
    "PLL/CaseObject/CreateCaseFromServiceRequest" |
    "PLL/CaseObject/DeleteCase" |
    "PLL/CaseObject/Move" |
    "PLL/CaseObject/Search" |
    "PLL/CaseObjectComments/Add" |
    "PLL/CaseObjectComments/ByCaObjectId" |
    "PLL/CaseObjectComments/Delete" |
    "PLL/CaseObjectComments/Update" |
    "PLL/CasePayment/Add" |
    "PLL/CasePayment/AddDeposit" |
    "PLL/CasePayment/ByCaObjectId" |
    "PLL/CasePayment/Delete" |
    "PLL/CasePayment/DeleteByCaObjectId" |
    "PLL/CasePayment/Search" |
    "PLL/CasePaymentRefund/Add" |
    "PLL/CasePaymentRefund/Delete" |
    "PLL/CasePaymentRefund/Search" |
    "PLL/CasePaymentRefund/Update" |
    "PLL/CasePeople/Add" |
    "PLL/CasePeople/ByCaObjectId" |
    "PLL/CasePeople/Delete" |
    "PLL/CasePeople/DeleteByCaObjectId" |
    "PLL/CasePeople/Search" |
    "PLL/CaseRelDocs/Add" |
    "PLL/CaseRelDocs/ByCaObjectId" |
    "PLL/CaseRelDocs/Delete" |
    "PLL/CaseRelDocs/DeleteByCaObjectId" |
    "PLL/CaseRelDocs/GetStoragePreferences" |
    "PLL/CaseRelDocs/Search" |
    "PLL/CaseStatus/Add" |
    "PLL/CaseTask/Add" |
    "PLL/CaseTask/ByCaObjectId" |
    "PLL/CaseTask/ByIds" |
    "PLL/CaseTask/Delete" |
    "PLL/CaseTask/DeleteByCaObjectId" |
    "PLL/CaseTask/Search" |
    "PLL/CaseTask/SetResult" |
    "PLL/CaseTask/Update" |
    "PLL/CaseTaskComments/Add" |
    "PLL/CaseTaskComments/ByCaTaskId" |
    "PLL/CaseTaskComments/ByCaTaskIds" |
    "PLL/CaseTaskComments/Delete" |
    "PLL/CaseTaskComments/Update" |
    "PLL/CaseTaskResults/Add" |
    "PLL/CaseTaskResults/ByCaTaskIds" |
    "PLL/CaseTaskResults/SearchObject" |
    "PLL/CaseType/Add" |
    "PLL/CaseType/GetList" |
    "PLL/CaseType/Search" |
    "PLL/CaseType/SearchObject" |
    "PLL/CaseType/Update" |
    "PLL/CaseViolations/Add" |
    "PLL/CaseViolations/ByCaObjectId" |
    "PLL/CaseViolations/ByCaObjectIds" |
    "PLL/CaseViolations/ByIds" |
    "PLL/CaseViolations/CompleteViolations" |
    "PLL/CaseViolations/Delete" |
    "PLL/CaseViolations/DeleteByCaObjectId" |
    "PLL/CaseViolations/Search" |
    "PLL/Department/Add" |
    "PLL/Deposit/All" |
    "PLL/Deposit/Search" |
    "PLL/Discipline/All" |
    "PLL/Division/Add" |
    "PLL/ExpirationType/Add" |
    "PLL/FeeSetup/All" |
    "PLL/FeeSetup/Search" |
    "PLL/GeneralComments/Add" |
    "PLL/GeneralComments/Delete" |
    "PLL/Holiday/Add" |
    "PLL/Holiday/Delete" |
    "PLL/InspectionTimeBlock/Add" |
    "PLL/NumberingGroup/Add" |
    "PLL/NumberingGroup/Update" |
    "PLL/People/Add" |
    "PLL/PeopleRole/Add" |
    "PLL/SubType/Add" |
    "PLL/SubType/Update" |
    "PLL/TaskResultDetail/Add" |
    "PLL/TaskResultDetail/Update" |
    "PLL/TaskResultFeeInsert/Add" |
    "PLL/TaskResultFeeInsert/Delete" |
    "PLL/TaskResultFeeInsert/DeleteByTaskId" |
    "PLL/TaskResultFeeInsert/Update" |
    "PLL/TenderType/Add" |
    "PLL/TenderType/Update" |
    string;

    /**
     * @description The data object to pass to the service operation. 
     */
    data?: any;
}

/** An interface that defines the outputs of the activity. */
export interface UseCityworksServiceOutputs {
    /**
     * @description The result of the service operation.
     */
    result?: any;
}

/**
 * @category Cityworks - General
 * @defaultName cwService
 * @description Utility activity to generically access any Cityworks REST API operation.
 */
export class UseCityworksService implements IActivityHandler {
    async execute(inputs: UseCityworksServiceInputs): Promise<UseCityworksServiceOutputs> {
        if (!inputs.service) {
            throw new Error("service is required");
        }
        if (!inputs.path) {
            throw new Error("path is required");
        }

        const response = await inputs.service.call(inputs.data || {}, inputs.path) as ServiceTypes.CoreResponseBase_<any>;
        checkResponse(response);

        return {
            result: response.Value,
        };
    }
}
